# Be sure to restart your server when you modify this file.
# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!
# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.
# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
#
# If you're using docker development evironment than the server addresses
# below should be fine. Otherwise you will have to replace some of the
# hostnames with localhost.
development:
  secret_key_base: SomeRandomStringOfCharactersYouNeedToReplaceThis
  aws:
    access_key_id: SomeRandomStringOfCharactersYouNeedToReplaceThis
    secret_access_key: SomeRandomStringOfCharactersYouNeedToReplaceThis
    region: us-east-1
  xl_server:
    base_url: http://localhost:22001
  memcache:
    server: memcached:11211
  redis:
    server: redis
    port: 6379
  recaptcha:
    site_key: SomeRandomStringOfCharactersYouNeedToReplaceThis
    secret_key: SomeRandomStringOfCharactersYouNeedToReplaceThis
  postmark:
    postmark_api_key: SomeRandomStringOfCharactersYouNeedToReplaceThis
test:
  secret_key_base: SomeRandomStringOfCharactersYouNeedToReplaceThis
  aws:
    access_key_id: SomeRandomStringOfCharactersYouNeedToReplaceThis
    secret_access_key: SomeRandomStringOfCharactersYouNeedToReplaceThis
    region: us-east-1
  google_authentication:
    integration-dev@vandegriftinc.com:
      client_id: SomeRandomStringOfCharactersYouNeedToReplaceThis.apps.googleusercontent.com
      client_secret: SomeRandomStringOfCharactersYouNeedToReplaceThis
      refresh_token: SomeRandomStringOfCharactersYouNeedToReplaceThis
  memcache:
    server: memcached:11211
  redis:
    server: redis
    port: 6379
