module OpenChain; module ModelFieldDefinition; module ProductVendorAssignmentFieldDefinition
  def add_product_vendor_assignment_fields
    add_fields CoreModule::PRODUCT_VENDOR_ASSIGNMENT, [
      # these ID fields are different than the ones generated by the make_*_arrays methods, because these are read only and
      # ok if the users see them
      [1,:prodven_vend_dbid,:vendor_id,"Vendor DB ID",{data_type: :integer,read_only:true}],
      [2,:prodven_prod_dbid,:product_id,"Product DB ID",{data_type: :integer,read_only:true}]
    ]
    add_fields CoreModule::PRODUCT_VENDOR_ASSIGNMENT, make_product_arrays(100,"prodven","product_vendor_assignments")
    add_fields CoreModule::PRODUCT_VENDOR_ASSIGNMENT, make_vendor_arrays(200,"prodven","product_vendor_assignments")
  end
end; end; end
