require 'open_chain/custom_handler/custom_definition_support'

module OpenChain; module CustomHandler; module LumberLiquidators; module LumberCustomDefinitionSupport
  CUSTOM_DEFINITION_INSTRUCTIONS = {
    cmp_sap_company: {label: 'SAP Company #', data_type: :string, module_type: 'Company', cdef_uid: "cmp_sap_company"},
    cmp_merch_coc_review: {label: 'Merch COC Review', data_type: :string, module_type: 'Company', cdef_uid: "cmp_merch_coc_review"},
    cmp_pc_approved_date: {label: 'PC Approved Date', data_type: :date, module_type: 'Company', cdef_uid: "cmp_pc_approved_date"},
    cmp_pc_approved_by: {label: 'PC Approved By', data_type: :integer, module_type: 'Company', cdef_uid: "cmp_pc_approved_by"},
    cmp_dba_name: {label: 'DBA Name', data_type: :string, module_type: 'Company', cdef_uid: "cmp_dba_name"},
    cmp_default_country_of_origin: {label: 'Default Country of Origin', data_type: :string, module_type: 'Company', cdef_uid: "cmp_default_country_of_origin"},
    cmp_default_handover_port: {label: 'Default Handover Port', data_type: :string, module_type: 'Company', cdef_uid: "cmp_default_handover_port"},
    cmp_default_inco_term: {label: 'Default INCO Term', data_type: :string, module_type: 'Company', cdef_uid: "cmp_default_inco_term"},
    cmp_requested_payment_method: {label: 'Requested Payment Method', data_type: :string, module_type: 'Company', cdef_uid: "cmp_requested_payment_method"},
    cmp_approved_payment_method: {label: 'Approved Payment Method', data_type: :string, module_type: 'Company', cdef_uid: "cmp_approved_payment_method"},
    cmp_us_vendor: {label: 'US Vendor', data_type: :string, module_type: 'Company', cdef_uid: "cmp_us_vendor"},
    cmp_vendor_type: {label: 'Vendor Type', data_type: :string, module_type: 'Company', cdef_uid: "cmp_vendor_type"},
    cmp_industry: {label: 'Industry', data_type: :string, module_type: 'Company', cdef_uid: "cmp_industry"},
    cmp_merch_approved_by: {label: 'Merch Approved By', data_type: :integer, module_type: 'Company', cdef_uid: "cmp_merch_approved_by"},
    cmp_merch_approved_date: {label: 'Merch Approved Date', data_type: :date, module_type: 'Company', cdef_uid: "cmp_merch_approved_date"},
    cmp_legal_approved_date: {label: 'Legal Approved Date', data_type: :date, module_type: 'Company', cdef_uid: "cmp_legal_approved_date"},
    cmp_legal_approved_by: {label: 'Legal Approved By', data_type: :integer, module_type: 'Company', cdef_uid: "cmp_legal_approved_by"},
    cmp_a_r_contact_name: {label: 'A/R Contact Name', data_type: :string, module_type: 'Company', cdef_uid: "cmp_a_r_contact_name"},
    cmp_a_r_contact_email: {label: 'A/R Contact Email', data_type: :string, module_type: 'Company', cdef_uid: "cmp_a_r_contact_email"},
    cmp_payment_terms: {label: 'Payment Terms', data_type: :string, module_type: 'Company', cdef_uid: "cmp_payment_terms"},
    cmp_purchasing_contact_name: {label: 'Purchasing Contact Name', data_type: :string, module_type: 'Company', cdef_uid: "cmp_purchasing_contact_name"},
    cmp_purchasing_contact_email: {label: 'Purchasing Contact Email', data_type: :string, module_type: 'Company', cdef_uid: "cmp_purchasing_contact_email"},
    cmp_payment_address: {label: 'Payment Address', data_type: :text, module_type: 'Company', cdef_uid: "cmp_payment_address"},
    cmp_business_address: {label: 'Business Address', data_type: :text, module_type: 'Company', cdef_uid: "cmp_business_address"},
    cmp_primary_phone: {label: 'Primary Phone', data_type: :string, module_type: 'Company', cdef_uid: "cmp_primary_phone"},
    cmp_primary_fax: {label: 'Primary Fax', data_type: :string, module_type: 'Company', cdef_uid: "cmp_primary_fax"},
    cmp_pc_approved_by_executive: {label: 'PC Approved By - Executive', data_type: :integer, module_type: 'Company', cdef_uid: "cmp_pc_approved_by_executive"},
    cmp_pc_approved_date_executive: {label: 'PC Approved Date - Executive', data_type: :date, module_type: 'Company', cdef_uid: "cmp_pc_approved_date_executive"},
    cmp_po_blocked: {label: 'PO Blocked', data_type: :boolean, module_type: 'Company', cdef_uid: "cmp_po_blocked"},
    cmp_sap_blocked_status: {label: 'SAP Blocked Status', data_type: :boolean, module_type: 'Company', cdef_uid: "cmp_sap_blocked_status"},
    cmp_vendor_agreement_review: {label: 'Vendor Agreement Review', data_type: :string, module_type: 'Company', cdef_uid: "cmp_vendor_agreement_review"},
    plnt_country_iso_code: {label: 'Country ISO Code', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_country_iso_code"},
    plnt_sap_coo_abbreviation: {label: 'SAP COO Abbreviation', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_sap_coo_abbreviation"},
    plnt_address: {label: 'Address', data_type: :text, module_type: 'Plant', cdef_uid: "plnt_address"},
    plnt_region: {label: 'Region', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_region"},
    plnt_mid_code: {label: 'MID Code', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_mid_code"},
    plnt_company_name_shipper: {label: 'Company Name - Shipper', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_company_name_shipper"},
    plnt_company_name_manufacturer: {label: 'Company Name - Manufacturer', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_company_name_manufacturer"},
    plnt_factory_contact_name: {label: 'Factory Contact Name', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_factory_contact_name"},
    plnt_factory_contact_phone: {label: 'Factory Contact Phone', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_factory_contact_phone"},
    plnt_factory_contact_email: {label: 'Factory Contact Email', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_factory_contact_email"},
    plnt_logistics_contact_name: {label: 'Logistics Contact Name', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_logistics_contact_name"},
    plnt_logistics_contact_phone: {label: 'Logistics Contact Phone', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_logistics_contact_phone"},
    plnt_logistics_contact_email: {label: 'Logistics Contact Email', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_logistics_contact_email"},
    plnt_mill_code: {label: 'Mill Code', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_mill_code"},
    plnt_default_origin_port: {label: 'Default Origin Port', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_default_origin_port"},
    plnt_alternate_loading_port: {label: 'Alternate Loading Port', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_alternate_loading_port"},
    plnt_po_notify_email: {label: 'PO Notify Email', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_po_notify_email"},
    plnt_merch_approved_by: {label: 'Merch Approved By', data_type: :integer, module_type: 'Plant', cdef_uid: "plnt_merch_approved_by"},
    plnt_merch_approved_date: {label: 'Merch Approved Date', data_type: :date, module_type: 'Plant', cdef_uid: "plnt_merch_approved_date"},
    plnt_tc_approved_by: {label: 'TC Approved By', data_type: :integer, module_type: 'Plant', cdef_uid: "plnt_tc_approved_by"},
    plnt_tc_approved_date: {label: 'TC Approved Date', data_type: :date, module_type: 'Plant', cdef_uid: "plnt_tc_approved_date"},
    plnt_pc_approved_by: {label: 'PC Approved By', data_type: :integer, module_type: 'Plant', cdef_uid: "plnt_pc_approved_by"},
    plnt_pc_approved_date: {label: 'PC Approved Date', data_type: :date, module_type: 'Plant', cdef_uid: "plnt_pc_approved_date"},
    plnt_triage_document_review: {label: 'Triage Document Review', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_triage_document_review"},
    plnt_triage_exec_review: {label: 'Triage Document Exec Review', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_triage_exec_review"},
    plnt_pc_approved_by_executive: {label: 'PC Approved By - Executive', data_type: :integer, module_type: 'Plant', cdef_uid: "plnt_pc_approved_by_executive"},
    plnt_pc_approved_date_executive: {label: 'PC Approved Date - Executive', data_type: :date, module_type: 'Plant', cdef_uid: "plnt_pc_approved_date_executive"},
    plnt_insurance_certificate_review: {label: 'Insurance Certificate Review', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_insurance_certificate_review"},
    plnt_dc_ship_to: {label: 'DC Ship To', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_dc_ship_to"},
    ppga_sample_coc_review: {label: 'Sample COC Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_sample_coc_review"},
    ppga_triage_document_review: {label: 'Triage Document Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_triage_document_review"},
    ppga_carb_certificate_review: {label: 'CARB Certificate Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_carb_certificate_review"},
    ppga_ca_01350_addendum_review: {label: 'CA-01350 Addendum Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ca_01350_addendum_review"},
    ppga_scgen_010_review: {label: 'SCGEN-010 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_scgen_010_review"},
    ppga_ts_130_review: {label: 'TS-130 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_130_review"},
    ppga_ts_241_review: {label: 'TS-241 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_241_review"},
    ppga_ts_242_review: {label: 'TS-242 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_242_review"},
    ppga_ts_282_review: {label: 'TS-282 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_282_review"},
    ppga_ts_330_review: {label: 'TS-330 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_330_review"},
    ppga_ts_331_review: {label: 'TS-331 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_331_review"},
    ppga_ts_342_review: {label: 'TS-342 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_342_review"},
    ppga_ts_399_review: {label: 'TS-399 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_399_review"},
    ppga_ul_csa_etl_review: {label: 'UL/CSA/ETL Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ul_csa_etl_review"},
    ppga_fda_certificate_accession_letter_review: {label: 'FDA Certificate & Accession Letter Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_fda_certificate_accession_letter_review"},
    ppga_ca_battery_charger_system_cert_review: {label: 'CA Battery Charger System Cert Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ca_battery_charger_system_cert_review"},
    ppga_formaldehyde_test_review: {label: 'Formaldehyde Test Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_formaldehyde_test_review"},
    ppga_phthalate_test_review: {label: 'Phthalate Test Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_phthalate_test_review"},
    ppga_heavy_metal_test_review: {label: 'Heavy Metal Test Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_heavy_metal_test_review"},
    ppga_lead_cadmium_test_review: {label: 'Lead & Cadmium Test Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_lead_cadmium_test_review"},
    ppga_lead_paint_review: {label: 'Lead Paint Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_lead_paint_review"},
    ppga_msds_review: {label: 'MSDS Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_msds_review"},
    ppga_merch_approved_by: {label: 'Merch Approved By', data_type: :integer, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_merch_approved_by"},
    ppga_merch_approved_date: {label: 'Merch Approved Date', data_type: :date, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_merch_approved_date"},
    ppga_qa_approved_by: {label: 'QA Approved By', data_type: :integer, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_qa_approved_by"},
    ppga_qa_approved_date: {label: 'QA Approved Date', data_type: :date, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_qa_approved_date"},
    ppga_pc_approved_by: {label: 'PC Approved By', data_type: :integer, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_pc_approved_by"},
    ppga_pc_approved_date: {label: 'PC Approved Date', data_type: :date, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_pc_approved_date"},
    ppga_pc_approved_by_executive: {label: 'PC Approved By - Executive', data_type: :integer, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_pc_approved_by_executive"},
    ppga_pc_approved_date_executive: {label: 'PC Approved Date - Executive', data_type: :date, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_pc_approved_date_executive"},
    prod_old_article: {label: 'Old Article #', data_type: :string, module_type: 'Product', cdef_uid: "prod_old_article"},
    prod_overall_thickness: {label: 'Overall Thickness', data_type: :string, module_type: 'Product', read_only: true, cdef_uid: "prod_overall_thickness"},
    prod_merch_cat: {label: "Merch Category", data_type: :string, module_type: 'Product', read_only: true, cdef_uid: "prod_merch_cat"},
    prod_merch_cat_desc: {label: "Merch Category Description", data_type: :string, module_type: 'Product', read_only: true, cdef_uid: "prod_merch_cat_desc"},
    prod_sap_extract: {label:'SAP Extract Date', data_type: :datetime, module_type: 'Product', cdef_uid: "prod_sap_extract"},
    class_proposed_hts: {label: "Proposed HTS", data_type: :string, module_type: "Classification", cdef_uid: "class_proposed_hts"},
    class_customs_description: {label: "Customs Description", data_type: :string, module_type: "Classification", cdef_uid: "class_customs_description"},
    prodven_carb: {label:'CARB Statement',data_type: :string, module_type:'ProductVendorAssignment', cdef_uid: "prodven_carb"},
    prodven_patent: {label:'Patent Statement',data_type: :string, module_type:'ProductVendorAssignment', cdef_uid: "prodven_patent"},
    prodven_risk: {label:'Risk',data_type: :string, module_type:'ProductVendorAssignment', cdef_uid: "prodven_risk"},
    pva_pc_approved_by: {label: 'PC Approved By', data_type: :integer, module_type: 'PlantVariantAssignment', cdef_uid: "pva_pc_approved_by"},
    pva_pc_approved_date: {label: 'PC Approved Date', data_type: :datetime, module_type: 'PlantVariantAssignment', cdef_uid: "pva_pc_approved_date"},
    ord_asn_arrived: {label: 'ASN - Arrived', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_arrived"},
    ord_asn_booking_approved: {label: 'ASN - Booking Approved', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_booking_approved"},
    ord_asn_booking_submitted: {label: 'ASN - Booking Submitted', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_booking_submitted"},
    ord_asn_departed: {label: 'ASN - Departed', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_departed"},
    ord_asn_discharged: {label: 'ASN - Discharged', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_discharged"},
    ord_asn_empty_return: {label: 'ASN - Empty Return', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_empty_return"},
    ord_asn_fcr_created: {label: 'ASN - FCR Created', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_fcr_created"},
    ord_asn_gate_in: {label: 'ASN - Full In Gate at Origin', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_gate_in"},
    ord_asn_gate_out: {label: 'ASN - Full Outgate - Discharge Port', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_gate_out"},
    ord_asn_loaded_at_port: {label: 'ASN - Loaded At Port', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_loaded_at_port"},
    ord_assigned_agent: {label: 'Assigned Agent', data_type: :string, module_type: 'Order', read_only: true, cdef_uid: "ord_assigned_agent"},
    ord_avail_to_prom_date: {label: 'Availabe To Promise Date', data_type: :date, module_type: 'Order', read_only: true, cdef_uid: "ord_avail_to_prom_date"},
    ord_comp_docs_posted_by: {label: 'Compliance Docs Posted By', data_type: :integer, module_type: 'Order', read_only: true, is_user: true, cdef_uid: "ord_comp_docs_posted_by"},
    ord_comp_docs_posted_date: {label: 'Compliance Docs Posted Date', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_comp_docs_posted_date"},
    ord_comp_docs_submitted_date: {label: 'Compliance Docs Submitted Date', data_type: :date, module_type: 'Order', cdef_uid: "ord_comp_docs_submitted_date"},
    ord_comp_docs_receipt_confirmed_date: {label: 'Compliance Docs Receipt Confirmed Date', data_type: :date, module_type: 'Order', cdef_uid: "ord_comp_docs_receipt_confirmed_date"},
    ord_customs_entry_note: {label:'Customs Entry Notes', data_type: :text, module_type: 'Order', cdef_uid: "ord_customs_entry_note"},
    ord_inspection_requested_date: {label: 'Inspection Requested Date', data_type: :date, module_type: 'Order', cdef_uid: "ord_inspection_requested_date"},
    ord_sap_extract: {label:'SAP Extract Date', data_type: :datetime, module_type: 'Order', cdef_uid: "ord_sap_extract"},
    ord_type: {label: 'Order Type', data_type: :string, module_type: 'Order', cdef_uid: "ord_type"},
    ord_buyer_name: {label: 'Buyer Name', data_type: :string, module_type: 'Order', cdef_uid: "ord_buyer_name"},
    ord_buyer_phone: {label: 'Buyer Phone', data_type: :string, module_type: 'Order', cdef_uid: "ord_buyer_phone"},
    ord_change_log: {label: 'Change Log', data_type: :text, module_type: 'Order', read_only:true, cdef_uid: "ord_change_log"},
    ord_country_of_origin: {label: 'Country of Origin', data_type: :string, module_type: 'Order', cdef_uid: "ord_country_of_origin"},
    ord_dhl_push_date: {label: "DHL PO Push Date", data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_dhl_push_date"},
    # this label is being changed in config migration 20161106, but we can't change it here yet because
    # the cdef_uid hasn't been created yet.  Once this is deployed to production, we can change the label so
    # it's less confusing for future readers (note, the hash key ord_forecasted_handover_date has to stay unless
    # you fix all references in the code)
    ord_forecasted_handover_date: {label: "Forecasted Ship Window End", data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_forecasted_ship_window_end"},
    ord_forecasted_ship_window_start: {label:"Forecasted Ship Window Start", data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_forecasted_ship_window_start"},
    ord_inspection_date_planned: {label: "Inspection Date - Planned", data_type: :date, module_type: "Order", cdef_uid: "ord_inspection_date_planned"},
    ord_inspection_date_completed: {label: "Inspection Date - Completed", data_type: :date, module_type: "Order", cdef_uid: "ord_inspection_date_completed"},
    ord_inspector_assigned: {label: "Inspector Assigned", data_type: :string, module_type: 'Order', cdef_uid: "ord_inspector_assigned"},
    ord_internal_production_articles: {label:"Internal Production - Articles Used", data_type: :text, module_type: "Order", cdef_uid: "ord_internal_production_articles"},
    ord_internal_production_orders: {label:"Internal Production - Orders Used", data_type: :text, module_type: "Order", cdef_uid: "ord_internal_production_orders"},
    ord_pc_approval_recommendation: {label: "PC Approval Recommendation", data_type: :string, module_type: 'Order', cdef_uid: "ord_pc_approval_recommendation"},
    ord_planned_expected_delivery_date: {label: "Planned Expected Delivery Date", data_type: :date, module_type: "Order", read_only:true, cdef_uid: "ord_planned_expected_delivery_date"},
    ord_planned_handover_date: {label: "Planned Handover Date", data_type: :date, module_type: "Order", cdef_uid: "ord_planned_handover_date"},
    ord_po_escalation: {label: "PO Escalation", data_type: :boolean, module_type: 'Order', cdef_uid: "ord_po_escalation"},
    ord_price_revised_date: {label: "Price Revised Date", data_type: :datetime, module_type:'Order',read_only: true, cdef_uid: "ord_price_revised_date"},
    ord_production_start_date_planned: {label: "Production Start Date - Planned", data_type: :date, module_type: 'Order', cdef_uid: "ord_production_start_date_planned"},
    ord_production_start_date_actual: {label: "Production Start Date - Actual", data_type: :date, module_type: 'Order', cdef_uid: "ord_production_start_date_actual"},
    ord_production_delay: {label: "Production Delay", data_type: :boolean, module_type: 'Order', cdef_uid: "ord_production_delay"},
    ord_production_delay_first_reported: {label: "Production Delay First Reported", data_type: :date, module_type: 'Order', cdef_uid: "ord_production_delay_first_reported"},
    ord_qa_hold_by: {label: "QA Hold By", data_type: :integer, module_type:'Order', is_user:true, read_only: true, cdef_uid: "ord_qa_hold_by"},
    ord_qa_hold_date: {label: "QA Hold Date", data_type: :datetime, module_type:'Order', read_only:true, cdef_uid: "ord_qa_hold_date"},
    ord_sap_vendor_handover_date: {label: 'SAP Vendor Handover Date', data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_sap_vendor_handover_date"},
    ord_ship_confirmation_date: {label: "Ship Confirmation Date", data_type: :date, module_type: "Order", read_only:true, cdef_uid: "ord_ship_confirmation_date"},
    ord_testing_date_planned: {label: "Testing Date - Planned", data_type: :date, module_type: "Order", cdef_uid: "ord_testing_date_planned"},
    ord_testing_date_completed: {label: "Testing Date - Completed", data_type: :date, module_type: "Order", cdef_uid: "ord_testing_date_completed"},
    ord_cancel_date: {label: "Cancelled Date", data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_cancel_date"},
    ord_manual_send_to_sap_date: {label: "Manual Send To SAP Date", data_type: :datetime, module_type: "Order", read_only: true, cdef_uid: "ord_manual_send_to_sap_date"},
    ord_total_freight: {label: 'Total Freight', data_type: :decimal, module_type: 'Order', read_only: true, cdef_uid: "ord_total_freight"},
    ord_grand_total: {label: 'Grand Total', data_type: :decimal, module_type: 'Order', read_only: true, cdef_uid: "ord_grand_total"},
    ord_delay_reason: { label: "Delay Reason", data_type: :string, module_type: "Order", cdef_uid: "ord_delay_reason"},
    ord_delay_dispo: { label: "Delay Disposition", data_type: :string, module_type: "Order", cdef_uid: "ord_delay_dispo"},
    ordln_old_art_number: { label: 'Old Article Number', data_type: :string, module_type: 'OrderLine', cdef_uid: "ordln_old_art_number"},
    ordln_part_name: {label: 'Part Name', data_type: :string, module_type: 'OrderLine', cdef_uid: "ordln_part_name"},
    ordln_pc_approved_by:  {label: 'PC Approved By', data_type: :integer, module_type: 'OrderLine', cdef_uid: "ordln_pc_approved_by"},
    ordln_pc_approved_date: {label: 'PC Approved Date', data_type: :datetime, module_type: 'OrderLine', cdef_uid: "ordln_pc_approved_date"},
    ordln_pc_approved_by_executive:  {label: 'PC Approved By - Executive', data_type: :integer, module_type: 'OrderLine', cdef_uid: "ordln_pc_approved_by_executive"},
    ordln_pc_approved_date_executive: {label: 'PC Approved Date - Executive', data_type: :datetime, module_type: 'OrderLine', cdef_uid: "ordln_pc_approved_date_executive"},
    ordln_price_revised_date: {label: "Price Revised Date", data_type: :datetime, module_type:'OrderLine',read_only: true, cdef_uid: "ordln_price_revised_date"},
    ordln_qa_approved_by: {label: 'QA Approved By', data_type: :integer, module_type: 'OrderLine', read_only: true, is_user: true, cdef_uid: "ordln_qa_approved_by"},
    ordln_qa_approved_date: {label: 'QA Approved DAte', data_type: :datetime, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_qa_approved_date"},
    ordln_custom_article_description: {label: 'Custom Article Description', data_type: :text, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_custom_article_description"},
    ordln_inland_freight_vendor_number: {label: 'Inland Freight Vendor Number', data_type: :string, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_inland_freight_vendor_number"},
    ordln_inland_freight_amount: {label: 'Inland Freight Amount', data_type: :decimal, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_inland_freight_amount"},
    ordln_vendor_inland_freight_amount: {label: 'Vendor Inland Freight Amount', data_type: :decimal, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_vendor_inland_freight_amount"},
    ordln_gross_weight_kg: {label: 'Gross Weight (KGS)', data_type: :decimal, module_type: 'OrderLine', cdef_uid: "ordln_gross_weight_kg"},
    var_recipe: {label: 'Recipe', data_type: :text, module_type: 'Variant', cdef_uid: "var_recipe"},
    shp_booking_unlocked_date: {label: "Booking Unlocked Date", data_type: :date, module_type: "Shipment", cdef_uid: "shp_booking_unlocked_date"}
  }

  def self.included(base)
    base.extend(::OpenChain::CustomHandler::CustomDefinitionSupport)
    base.extend(ClassMethods)
  end

  module ClassMethods
    def prep_custom_definitions fields
      prep_custom_defs fields, CUSTOM_DEFINITION_INSTRUCTIONS
    end
  end
end; end; end; end
