require 'open_chain/custom_handler/custom_definition_support'

module OpenChain; module CustomHandler; module LumberLiquidators; module LumberCustomDefinitionSupport
  CUSTOM_DEFINITION_INSTRUCTIONS = {
    cmp_sap_company: {label: 'SAP Company #', data_type: :string, module_type: 'Company', cdef_uid: "cmp_sap_company"},
    cmp_merch_coc_review: {label: 'Merch COC Review', data_type: :string, module_type: 'Company', cdef_uid: "cmp_merch_coc_review"},
    cmp_pc_approved_date: {label: 'PC Approved Date', data_type: :date, module_type: 'Company', cdef_uid: "cmp_pc_approved_date"},
    cmp_pc_approved_by: {label: 'PC Approved By', data_type: :integer, module_type: 'Company', cdef_uid: "cmp_pc_approved_by"},
    cmp_dba_name: {label: 'DBA Name', data_type: :string, module_type: 'Company', cdef_uid: "cmp_dba_name"},
    cmp_default_country_of_origin: {label: 'Default Country of Origin', data_type: :string, module_type: 'Company', cdef_uid: "cmp_default_country_of_origin"},
    cmp_default_handover_port: {label: 'Default Handover Port', data_type: :string, module_type: 'Company', cdef_uid: "cmp_default_handover_port"},
    cmp_default_inco_term: {label: 'Default INCO Term', data_type: :string, module_type: 'Company', cdef_uid: "cmp_default_inco_term"},
    cmp_requested_payment_method: {label: 'Requested Payment Method', data_type: :string, module_type: 'Company', cdef_uid: "cmp_requested_payment_method"},
    cmp_approved_payment_method: {label: 'Approved Payment Method', data_type: :string, module_type: 'Company', cdef_uid: "cmp_approved_payment_method"},
    cmp_us_vendor: {label: 'US Vendor', data_type: :string, module_type: 'Company', cdef_uid: "cmp_us_vendor"},
    cmp_vendor_type: {label: 'Vendor Type', data_type: :string, module_type: 'Company', cdef_uid: "cmp_vendor_type"},
    cmp_industry: {label: 'Industry', data_type: :string, module_type: 'Company', cdef_uid: "cmp_industry"},
    cmp_merch_approved_by: {label: 'Merch Approved By', data_type: :integer, module_type: 'Company', cdef_uid: "cmp_merch_approved_by"},
    cmp_merch_approved_date: {label: 'Merch Approved Date', data_type: :date, module_type: 'Company', cdef_uid: "cmp_merch_approved_date"},
    cmp_legal_approved_date: {label: 'Legal Approved Date', data_type: :date, module_type: 'Company', cdef_uid: "cmp_legal_approved_date"},
    cmp_legal_approved_by: {label: 'Legal Approved By', data_type: :integer, module_type: 'Company', cdef_uid: "cmp_legal_approved_by"},
    cmp_a_r_contact_name: {label: 'A/R Contact Name', data_type: :string, module_type: 'Company', cdef_uid: "cmp_a_r_contact_name"},
    cmp_a_r_contact_email: {label: 'A/R Contact Email', data_type: :string, module_type: 'Company', cdef_uid: "cmp_a_r_contact_email"},
    cmp_payment_terms: {label: 'Payment Terms', data_type: :string, module_type: 'Company', cdef_uid: "cmp_payment_terms"},
    cmp_purchasing_contact_name: {label: 'Purchasing Contact Name', data_type: :string, module_type: 'Company', cdef_uid: "cmp_purchasing_contact_name"},
    cmp_purchasing_contact_email: {label: 'Purchasing Contact Email', data_type: :string, module_type: 'Company', cdef_uid: "cmp_purchasing_contact_email"},
    cmp_payment_address: {label: 'Payment Address', data_type: :text, module_type: 'Company', cdef_uid: "cmp_payment_address"},
    cmp_business_address: {label: 'Business Address', data_type: :text, module_type: 'Company', cdef_uid: "cmp_business_address"},
    cmp_primary_phone: {label: 'Primary Phone', data_type: :string, module_type: 'Company', cdef_uid: "cmp_primary_phone"},
    cmp_primary_fax: {label: 'Primary Fax', data_type: :string, module_type: 'Company', cdef_uid: "cmp_primary_fax"},
    cmp_pc_approved_by_executive: {label: 'PC Approved By - Executive', data_type: :integer, module_type: 'Company', cdef_uid: "cmp_pc_approved_by_executive"},
    cmp_pc_approved_date_executive: {label: 'PC Approved Date - Executive', data_type: :date, module_type: 'Company', cdef_uid: "cmp_pc_approved_date_executive"},
    cmp_po_blocked: {label: 'PO Blocked', data_type: :boolean, module_type: 'Company', cdef_uid: "cmp_po_blocked"},
    cmp_sap_blocked_status: {label: 'SAP Blocked Status', data_type: :boolean, module_type: 'Company', cdef_uid: "cmp_sap_blocked_status"},
    cmp_vendor_agreement_review: {label: 'Vendor Agreement Review', data_type: :string, module_type: 'Company', cdef_uid: "cmp_vendor_agreement_review"},
    plnt_country_iso_code: {label: 'Country ISO Code', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_country_iso_code"},
    plnt_sap_coo_abbreviation: {label: 'SAP COO Abbreviation', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_sap_coo_abbreviation"},
    plnt_address: {label: 'Address', data_type: :text, module_type: 'Plant', cdef_uid: "plnt_address"},
    plnt_region: {label: 'Region', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_region"},
    plnt_mid_code: {label: 'MID Code', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_mid_code"},
    plnt_company_name_shipper: {label: 'Company Name - Shipper', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_company_name_shipper"},
    plnt_company_name_manufacturer: {label: 'Company Name - Manufacturer', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_company_name_manufacturer"},
    plnt_factory_contact_name: {label: 'Factory Contact Name', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_factory_contact_name"},
    plnt_factory_contact_phone: {label: 'Factory Contact Phone', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_factory_contact_phone"},
    plnt_factory_contact_email: {label: 'Factory Contact Email', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_factory_contact_email"},
    plnt_logistics_contact_name: {label: 'Logistics Contact Name', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_logistics_contact_name"},
    plnt_logistics_contact_phone: {label: 'Logistics Contact Phone', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_logistics_contact_phone"},
    plnt_logistics_contact_email: {label: 'Logistics Contact Email', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_logistics_contact_email"},
    plnt_mill_code: {label: 'Mill Code', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_mill_code"},
    plnt_default_origin_port: {label: 'Default Origin Port', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_default_origin_port"},
    plnt_alternate_loading_port: {label: 'Alternate Loading Port', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_alternate_loading_port"},
    plnt_po_notify_email: {label: 'PO Notify Email', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_po_notify_email"},
    plnt_merch_approved_by: {label: 'Merch Approved By', data_type: :integer, module_type: 'Plant', cdef_uid: "plnt_merch_approved_by"},
    plnt_merch_approved_date: {label: 'Merch Approved Date', data_type: :date, module_type: 'Plant', cdef_uid: "plnt_merch_approved_date"},
    plnt_tc_approved_by: {label: 'TC Approved By', data_type: :integer, module_type: 'Plant', cdef_uid: "plnt_tc_approved_by"},
    plnt_tc_approved_date: {label: 'TC Approved Date', data_type: :date, module_type: 'Plant', cdef_uid: "plnt_tc_approved_date"},
    plnt_pc_approved_by: {label: 'PC Approved By', data_type: :integer, module_type: 'Plant', cdef_uid: "plnt_pc_approved_by"},
    plnt_pc_approved_date: {label: 'PC Approved Date', data_type: :date, module_type: 'Plant', cdef_uid: "plnt_pc_approved_date"},
    plnt_triage_document_review: {label: 'Triage Document Review', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_triage_document_review"},
    plnt_triage_exec_review: {label: 'Triage Document Exec Review', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_triage_exec_review"},
    plnt_pc_approved_by_executive: {label: 'PC Approved By - Executive', data_type: :integer, module_type: 'Plant', cdef_uid: "plnt_pc_approved_by_executive"},
    plnt_pc_approved_date_executive: {label: 'PC Approved Date - Executive', data_type: :date, module_type: 'Plant', cdef_uid: "plnt_pc_approved_date_executive"},
    plnt_insurance_certificate_review: {label: 'Insurance Certificate Review', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_insurance_certificate_review"},
    plnt_dc_ship_to: {label: 'DC Ship To', data_type: :string, module_type: 'Plant', cdef_uid: "plnt_dc_ship_to"},
    ppga_sample_coc_review: {label: 'Sample COC Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_sample_coc_review"},
    ppga_triage_document_review: {label: 'Triage Document Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_triage_document_review"},
    ppga_carb_certificate_review: {label: 'CARB Certificate Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_carb_certificate_review"},
    ppga_ca_01350_addendum_review: {label: 'CA-01350 Addendum Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ca_01350_addendum_review"},
    ppga_scgen_010_review: {label: 'SCGEN-010 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_scgen_010_review"},
    ppga_ts_130_review: {label: 'TS-130 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_130_review"},
    ppga_ts_241_review: {label: 'TS-241 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_241_review"},
    ppga_ts_242_review: {label: 'TS-242 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_242_review"},
    ppga_ts_282_review: {label: 'TS-282 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_282_review"},
    ppga_ts_330_review: {label: 'TS-330 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_330_review"},
    ppga_ts_331_review: {label: 'TS-331 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_331_review"},
    ppga_ts_342_review: {label: 'TS-342 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_342_review"},
    ppga_ts_399_review: {label: 'TS-399 Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ts_399_review"},
    ppga_ul_csa_etl_review: {label: 'UL/CSA/ETL Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ul_csa_etl_review"},
    ppga_fda_certificate_accession_letter_review: {label: 'FDA Certificate & Accession Letter Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_fda_certificate_accession_letter_review"},
    ppga_ca_battery_charger_system_cert_review: {label: 'CA Battery Charger System Cert Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_ca_battery_charger_system_cert_review"},
    ppga_formaldehyde_test_review: {label: 'Formaldehyde Test Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_formaldehyde_test_review"},
    ppga_phthalate_test_review: {label: 'Phthalate Test Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_phthalate_test_review"},
    ppga_heavy_metal_test_review: {label: 'Heavy Metal Test Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_heavy_metal_test_review"},
    ppga_lead_cadmium_test_review: {label: 'Lead & Cadmium Test Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_lead_cadmium_test_review"},
    ppga_lead_paint_review: {label: 'Lead Paint Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_lead_paint_review"},
    ppga_msds_review: {label: 'MSDS Review', data_type: :string, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_msds_review"},
    ppga_merch_approved_by: {label: 'Merch Approved By', data_type: :integer, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_merch_approved_by"},
    ppga_merch_approved_date: {label: 'Merch Approved Date', data_type: :date, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_merch_approved_date"},
    ppga_qa_approved_by: {label: 'QA Approved By', data_type: :integer, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_qa_approved_by"},
    ppga_qa_approved_date: {label: 'QA Approved Date', data_type: :date, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_qa_approved_date"},
    ppga_pc_approved_by: {label: 'PC Approved By', data_type: :integer, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_pc_approved_by"},
    ppga_pc_approved_date: {label: 'PC Approved Date', data_type: :date, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_pc_approved_date"},
    ppga_pc_approved_by_executive: {label: 'PC Approved By - Executive', data_type: :integer, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_pc_approved_by_executive"},
    ppga_pc_approved_date_executive: {label: 'PC Approved Date - Executive', data_type: :date, module_type: 'PlantProductGroupAssignment', cdef_uid: "ppga_pc_approved_date_executive"},
    prod_old_article: {label: 'Old Article #', data_type: :string, module_type: 'Product', cdef_uid: "prod_old_article"},
    prod_overall_thickness: {label: 'Overall Thickness', data_type: :string, module_type: 'Product', read_only: true, cdef_uid: "prod_overall_thickness"},
    prod_merch_cat: {label: "Merch Category", data_type: :string, module_type: 'Product', read_only: true, cdef_uid: "prod_merch_cat"},
    prod_merch_cat_desc: {label: "Merch Category Description", data_type: :string, module_type: 'Product', read_only: true, cdef_uid: "prod_merch_cat_desc"},
    prod_sap_extract: {label:'SAP Extract Date', data_type: :datetime, module_type: 'Product', cdef_uid: "prod_sap_extract"},
    prod_country_of_origin: {label: 'Country of Origin', data_type: :string, module_type: 'Product', cdef_uid: "prod_country_of_origin"},
    class_proposed_hts: {label: "Proposed HTS", data_type: :string, module_type: "Classification", cdef_uid: "class_proposed_hts"},
    class_customs_description: {label: "Customs Description", data_type: :string, module_type: "Classification", cdef_uid: "class_customs_description"},
    # The following 2 fields should no longer be used...they are legacy fields #
    prodven_carb: {label:'CARB Statement',data_type: :string, module_type:'ProductVendorAssignment', cdef_uid: "prodven_carb", read_only: true},
    prodven_patent: {label:'Patent Statement',data_type: :string, module_type:'ProductVendorAssignment', cdef_uid: "prodven_patent", read_only: true},
    # END LEGACY FIELDS #
    prodven_carb_statements: {label:'CARB Statements',data_type: :text, module_type:'ProductVendorAssignment', cdef_uid: "prodven_carb_statements", virtual_value_query: "SELECT GROUP_CONCAT(DISTINCT CONCAT(constant_text, ' - ', DATE_FORMAT(effective_date_start, '%Y-%m-%d')) ORDER BY effective_date_start SEPARATOR '\n ') FROM constant_texts WHERE text_type = 'CARB Statement' AND constant_textable_id = \#{customizable_id} AND constant_textable_type = 'ProductVendorAssignment'", virtual_search_query: "SELECT GROUP_CONCAT(DISTINCT CONCAT(constant_text, ' - ', DATE_FORMAT(effective_date_start, '%Y-%m-%d')) ORDER BY effective_date_start SEPARATOR '\n ') FROM constant_texts WHERE text_type = 'CARB Statement' AND constant_textable_id = product_vendor_assignments.id and constant_textable_type = 'ProductVendorAssignment'"},
    prodven_patent_statements: {label:'Patent Statements',data_type: :text, module_type:'ProductVendorAssignment', cdef_uid: "prodven_patent_statements", virtual_value_query: "SELECT GROUP_CONCAT(DISTINCT CONCAT(constant_text, ' - ', DATE_FORMAT(effective_date_start, '%Y-%m-%d')) ORDER BY effective_date_start SEPARATOR '\n ') FROM constant_texts WHERE text_type = 'Patent Statement' AND constant_textable_id = \#{customizable_id} AND constant_textable_type = 'ProductVendorAssignment'", virtual_search_query: "SELECT GROUP_CONCAT(DISTINCT CONCAT(constant_text, ' - ', DATE_FORMAT(effective_date_start, '%Y-%m-%d')) ORDER BY effective_date_start SEPARATOR '\n ') FROM constant_texts WHERE text_type = 'Patent Statement' AND constant_textable_id = product_vendor_assignments.id and constant_textable_type = 'ProductVendorAssignment'"},
    prodven_risk: {label:'Risk',data_type: :string, module_type:'ProductVendorAssignment', cdef_uid: "prodven_risk"},
    pva_pc_approved_by: {label: 'PC Approved By', data_type: :integer, module_type: 'PlantVariantAssignment', cdef_uid: "pva_pc_approved_by"},
    pva_pc_approved_date: {label: 'PC Approved Date', data_type: :datetime, module_type: 'PlantVariantAssignment', cdef_uid: "pva_pc_approved_date"},
    ord_asn_arrived: {label: 'ASN - Arrived', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_arrived"},
    ord_asn_booking_approved: {label: 'ASN - Booking Approved', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_booking_approved"},
    ord_asn_booking_submitted: {label: 'ASN - Booking Submitted', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_booking_submitted"},
    ord_asn_departed: {label: 'ASN - Departed', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_departed"},
    ord_asn_discharged: {label: 'ASN - Discharged', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_discharged"},
    ord_asn_empty_return: {label: 'ASN - Empty Return', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_empty_return"},
    ord_asn_fcr_created: {label: 'ASN - FCR Created', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_fcr_created"},
    ord_asn_gate_in: {label: 'ASN - Full In Gate at Origin', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_gate_in"},
    ord_asn_gate_out: {label: 'ASN - Full Outgate - Discharge Port', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_gate_out"},
    ord_asn_loaded_at_port: {label: 'ASN - Loaded At Port', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_loaded_at_port"},
    ord_asn_empty_out_gate_at_origin: {label: 'ASN - Empty Out Gate at Origin', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_empty_out_gate_at_origin"},
    ord_asn_est_arrival_discharge: {label: 'ASN - Est Arrival Discharge', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_est_arrival_discharge"},
    ord_asn_est_departure: {label: 'ASN - Est Departure', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_est_departure"},
    ord_asn_delivered: {label: 'ASN - Delivered', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_delivered"},
    ord_asn_container_unloaded: {label: 'ASN - Container Unloaded', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_container_unloaded"},
    ord_asn_carrier_released: {label: 'ASN - Carrier Released', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_carrier_released"},
    ord_asn_customs_released_carrier: {label: 'ASN - Customs Released Carrier', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_customs_released_carrier"},
    ord_asn_available_for_delivery: {label: 'ASN - Available for Delivery', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_available_for_delivery"},
    ord_asn_full_ingate: {label: 'ASN - Full Ingate', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_full_ingate"},
    ord_asn_on_rail_destination: {label: 'ASN - On Rail Destination', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_on_rail_destination"},
    ord_asn_rail_arrived_destination: {label: 'ASN - Rail Arrived (Destination)', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_rail_arrived_destination"},
    ord_asn_arrive_at_transship_port: {label: 'ASN - Arrive at Transship Port', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_arrive_at_transship_port"},
    ord_asn_depart_from_transship_port: {label: 'ASN - Depart from Tranship Port', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_depart_from_transship_port"},
    ord_asn_barge_depart: {label: 'ASN - Barge Depart', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_barge_depart"},
    ord_asn_barge_arrive: {label: 'ASN - Barge Arrive', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_asn_barge_arrive"},
    ord_assigned_agent: {label: 'Assigned Agent', data_type: :string, module_type: 'Order', read_only: true, cdef_uid: "ord_assigned_agent"},
    ord_avail_to_prom_date: {label: 'Availabe To Promise Date', data_type: :date, module_type: 'Order', read_only: true, cdef_uid: "ord_avail_to_prom_date"},
    ord_comp_docs_posted_by: {label: 'Compliance Docs Posted By', data_type: :integer, module_type: 'Order', read_only: true, is_user: true, cdef_uid: "ord_comp_docs_posted_by"},
    ord_comp_docs_posted_date: {label: 'Compliance Docs Posted Date', data_type: :datetime, module_type: 'Order', read_only: true, cdef_uid: "ord_comp_docs_posted_date"},
    ord_comp_docs_submitted_date: {label: 'Compliance Docs Submitted Date', data_type: :date, module_type: 'Order', cdef_uid: "ord_comp_docs_submitted_date"},
    ord_comp_docs_receipt_confirmed_date: {label: 'Compliance Docs Receipt Confirmed Date', data_type: :date, module_type: 'Order', cdef_uid: "ord_comp_docs_receipt_confirmed_date"},
    ord_customs_entry_note: {label:'Customs Entry Notes', data_type: :text, module_type: 'Order', cdef_uid: "ord_customs_entry_note"},
    ord_inspection_requested_date: {label: 'Inspection Requested Date', data_type: :date, module_type: 'Order', cdef_uid: "ord_inspection_requested_date"},
    ord_sap_extract: {label:'SAP Extract Date', data_type: :datetime, module_type: 'Order', cdef_uid: "ord_sap_extract"},
    ord_type: {label: 'Order Type', data_type: :string, module_type: 'Order', cdef_uid: "ord_type"},
    ord_buyer_name: {label: 'Buyer Name', data_type: :string, module_type: 'Order', cdef_uid: "ord_buyer_name"},
    ord_buyer_phone: {label: 'Buyer Phone', data_type: :string, module_type: 'Order', cdef_uid: "ord_buyer_phone"},
    ord_change_log: {label: 'Change Log', data_type: :text, module_type: 'Order', read_only:true, cdef_uid: "ord_change_log"},
    ord_country_of_origin: {label: 'Country of Origin', data_type: :string, module_type: 'Order', cdef_uid: "ord_country_of_origin"},
    ord_dhl_push_date: {label: "DHL PO Push Date", data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_dhl_push_date"},
    # this label is being changed in config migration 20161106, but we can't change it here yet because
    # the cdef_uid hasn't been created yet.  Once this is deployed to production, we can change the label so
    # it's less confusing for future readers (note, the hash key ord_forecasted_handover_date has to stay unless
    # you fix all references in the code)
    ord_forecasted_handover_date: {label: "Forecasted Ship Window End", data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_forecasted_ship_window_end"},
    ord_forecasted_ship_window_start: {label:"Forecasted Ship Window Start", data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_forecasted_ship_window_start"},
    ord_inspection_date_planned: {label: "Inspection Date - Planned", data_type: :date, module_type: "Order", cdef_uid: "ord_inspection_date_planned"},
    ord_inspection_date_completed: {label: "Inspection Date - Completed", data_type: :date, module_type: "Order", cdef_uid: "ord_inspection_date_completed"},
    ord_inspector_assigned: {label: "Inspector Assigned", data_type: :string, module_type: 'Order', cdef_uid: "ord_inspector_assigned"},
    ord_internal_production_articles: {label:"Internal Production - Articles Used", data_type: :text, module_type: "Order", cdef_uid: "ord_internal_production_articles"},
    ord_internal_production_orders: {label:"Internal Production - Orders Used", data_type: :text, module_type: "Order", cdef_uid: "ord_internal_production_orders"},
    ord_pc_approval_recommendation: {label: "PC Approval Recommendation", data_type: :string, module_type: 'Order', cdef_uid: "ord_pc_approval_recommendation"},
    ord_planned_expected_delivery_date: {label: "Planned Expected Delivery Date", data_type: :date, module_type: "Order", read_only:true, cdef_uid: "ord_planned_expected_delivery_date"},
    ord_planned_handover_date: {label: "Planned Handover Date", data_type: :date, module_type: "Order", cdef_uid: "ord_planned_handover_date"},
    ord_po_escalation: {label: "PO Escalation", data_type: :boolean, module_type: 'Order', cdef_uid: "ord_po_escalation"},
    ord_price_revised_date: {label: "Price Revised Date", data_type: :datetime, module_type:'Order',read_only: true, cdef_uid: "ord_price_revised_date"},
    ord_production_start_date_planned: {label: "Production Start Date - Planned", data_type: :date, module_type: 'Order', cdef_uid: "ord_production_start_date_planned"},
    ord_production_start_date_actual: {label: "Production Start Date - Actual", data_type: :date, module_type: 'Order', cdef_uid: "ord_production_start_date_actual"},
    ord_production_delay: {label: "Production Delay", data_type: :boolean, module_type: 'Order', cdef_uid: "ord_production_delay"},
    ord_production_delay_first_reported: {label: "Production Delay First Reported", data_type: :date, module_type: 'Order', cdef_uid: "ord_production_delay_first_reported"},
    ord_qa_hold_by: {label: "QA Hold By", data_type: :integer, module_type:'Order', is_user:true, read_only: true, cdef_uid: "ord_qa_hold_by"},
    ord_qa_hold_date: {label: "QA Hold Date", data_type: :datetime, module_type:'Order', read_only:true, cdef_uid: "ord_qa_hold_date"},
    ord_sap_vendor_handover_date: {label: 'SAP Vendor Handover Date', data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_sap_vendor_handover_date"},
    ord_ship_confirmation_date: {label: "Ship Confirmation Date", data_type: :date, module_type: "Order", read_only:true, cdef_uid: "ord_ship_confirmation_date"},
    ord_testing_date_planned: {label: "Testing Date - Planned", data_type: :date, module_type: "Order", cdef_uid: "ord_testing_date_planned"},
    ord_testing_date_completed: {label: "Testing Date - Completed", data_type: :date, module_type: "Order", cdef_uid: "ord_testing_date_completed"},
    ord_cancel_date: {label: "Cancelled Date", data_type: :date, module_type: "Order", read_only: true, cdef_uid: "ord_cancel_date"},
    ord_manual_send_to_sap_date: {label: "Manual Send To SAP Date", data_type: :datetime, module_type: "Order", read_only: true, cdef_uid: "ord_manual_send_to_sap_date"},
    ord_total_freight: {label: 'Total Freight', data_type: :decimal, module_type: 'Order', read_only: true, cdef_uid: "ord_total_freight"},
    ord_grand_total: {label: 'Grand Total', data_type: :decimal, module_type: 'Order', read_only: true, cdef_uid: "ord_grand_total"},
    ord_delay_reason: { label: "Delay Reason", data_type: :string, module_type: "Order", cdef_uid: "ord_delay_reason"},
    ord_delay_dispo: { label: "Delay Disposition", data_type: :string, module_type: "Order", cdef_uid: "ord_delay_dispo"},
    ord_bill_of_lading: { label: "BOL Number", data_type: :string, module_type: "Order", cdef_uid: "ord_bill_of_lading"},
    ord_bol_date: {label: "BOL Date", data_type: :datetime, module_type: "Order", cdef_uid: "ord_bol_date"},
    ord_snapshot_discrepancy_comment: {label: 'Snapshot Discrepancy Comment', data_type: :text, module_type: 'Order', cdef_uid: "ord_snapshot_discrepancy_comment"},
    ord_shipment_reference: {label: "Shipment Reference Number", data_type: :string, module_type: "Order", cdef_uid: "ord_shipment_reference", read_only: true},
    ord_shipment_cargo_ready_date: {label: "Cargo Ready Date", data_type: :date, module_type: "Order", cdef_uid: "ord_shipment_cargo_ready_date", read_only: true},
    ord_shipment_booking_requested_date: {label: "Booking Requested Date", data_type: :date, module_type: "Order", cdef_uid: "ord_shipment_booking_requested_date", read_only: true},
    ord_shipment_booking_number: {label: "Booking Number", data_type: :string, module_type: "Order", cdef_uid: "ord_shipment_booking_number", read_only: true},
    ord_shipment_sent_to_carrier_date: {label: "Sent To Carrier Date", data_type: :date, module_type: "Order", cdef_uid: "ord_shipment_sent_to_carrier_date", read_only: true},
    ord_shipment_booking_confirmed_date: {label: "Booking Confirmed Date", data_type: :date, module_type: "Order", cdef_uid: "ord_shipment_booking_confirmed_date", read_only: true},
    ord_shipment_booking_cutoff_date: {label: "Booking Cutoff Date", data_type: :date, module_type: "Order", cdef_uid: "ord_shipment_booking_cutoff_date", read_only: true},
    ordln_old_art_number: { label: 'Old Article Number', data_type: :string, module_type: 'OrderLine', cdef_uid: "ordln_old_art_number"},
    ordln_part_name: {label: 'Part Name', data_type: :string, module_type: 'OrderLine', cdef_uid: "ordln_part_name"},
    ordln_pc_approved_by:  {label: 'PC Approved By', data_type: :integer, module_type: 'OrderLine', cdef_uid: "ordln_pc_approved_by"},
    ordln_pc_approved_date: {label: 'PC Approved Date', data_type: :datetime, module_type: 'OrderLine', cdef_uid: "ordln_pc_approved_date"},
    ordln_pc_approved_by_executive:  {label: 'PC Approved By - Executive', data_type: :integer, module_type: 'OrderLine', cdef_uid: "ordln_pc_approved_by_executive"},
    ordln_pc_approved_date_executive: {label: 'PC Approved Date - Executive', data_type: :datetime, module_type: 'OrderLine', cdef_uid: "ordln_pc_approved_date_executive"},
    ordln_price_revised_date: {label: "Price Revised Date", data_type: :datetime, module_type:'OrderLine',read_only: true, cdef_uid: "ordln_price_revised_date"},
    ordln_qa_approved_by: {label: 'QA Approved By', data_type: :integer, module_type: 'OrderLine', read_only: true, is_user: true, cdef_uid: "ordln_qa_approved_by"},
    ordln_qa_approved_date: {label: 'QA Approved DAte', data_type: :datetime, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_qa_approved_date"},
    ordln_custom_article_description: {label: 'Custom Article Description', data_type: :text, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_custom_article_description"},
    ordln_inland_freight_vendor_number: {label: 'Inland Freight Vendor Number', data_type: :string, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_inland_freight_vendor_number"},
    ordln_inland_freight_amount: {label: 'Inland Freight Amount', data_type: :decimal, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_inland_freight_amount"},
    ordln_vendor_inland_freight_amount: {label: 'Vendor Inland Freight Amount', data_type: :decimal, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_vendor_inland_freight_amount"},
    ordln_gross_weight_kg: {label: 'Gross Weight (KGS)', data_type: :decimal, module_type: 'OrderLine', cdef_uid: "ordln_gross_weight_kg"},
    ordln_shpln_line_number: {label: 'Shipment Line - Line #', data_type: :integer, module_type: 'OrderLine', cdef_uid: "ordln_shpln_line_number"},
    ordln_shpln_product: {label: 'Shipment Line - Product', data_type: :string, module_type: 'OrderLine', cdef_uid: "ordln_shpln_product"},
    ordln_shpln_quantity: {label: 'Shipment Line - Quantity', data_type: :decimal, module_type: 'OrderLine', cdef_uid: "ordln_shpln_quantity"},
    ordln_shpln_cartons: {label: 'Shipment Line - Cartons', data_type: :integer, module_type: 'OrderLine', cdef_uid: "ordln_shpln_cartons"},
    ordln_shpln_volume: {label: 'Shipment Line - Volume (CBMS)', data_type: :decimal, module_type: 'OrderLine', cdef_uid: "ordln_shpln_volume"},
    ordln_shpln_gross_weight: {label: 'Shipment Line - Gross Weight (KGS)', data_type: :decimal, module_type: 'OrderLine', cdef_uid: "ordln_shpln_gross_weight"},
    ordln_shpln_container_number: {label: 'Shipment Line - Container', data_type: :string, module_type: 'OrderLine', cdef_uid: "ordln_shpln_container_number"},
    ordln_deleted_flag: {label: 'Deleted Flag', data_type: :boolean, module_type: 'OrderLine', read_only: true, cdef_uid: "ordln_deleted_flag"},
    ordln_po_create_article: {label: "PO Created - Article Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_create_article", read_only: true},
    ordln_po_create_quantity: {label: "PO Created - Quantity", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_create_quantity", read_only: true},
    ordln_po_create_hts: {label: "PO Created - HTS", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_create_hts", read_only: true},
    ordln_po_create_price_per_unit: {label: "PO Created - Price / Unit", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_create_price_per_unit", read_only: true},
    ordln_po_create_total_price: {label: "PO Created - Total Price", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_create_total_price", read_only: true},
    ordln_po_create_country_origin: {label: "PO Created - Country of Origin", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_create_country_origin", read_only: true},
    ordln_po_create_bol: {label: "PO Created - BOL", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_create_bol", read_only: true},
    ordln_po_create_container_number: {label: "PO Created - Container Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_create_container_number", read_only: true},
    ordln_po_create_seal_number: {label: "PO Created - Seal Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_create_seal_number", read_only: true},
    ordln_po_booked_article: {label: "PO Booked - Article Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_booked_article", read_only: true},
    ordln_po_booked_quantity: {label: "PO Booked - Quantity", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_booked_quantity", read_only: true},
    ordln_po_booked_hts: {label: "PO Booked - HTS", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_booked_hts", read_only: true},
    ordln_po_booked_price_per_unit: {label: "PO Booked - Price / Unit", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_booked_price_per_unit", read_only: true},
    ordln_po_booked_total_price: {label: "PO Booked - Total Price", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_booked_total_price", read_only: true},
    ordln_po_booked_country_origin: {label: "PO Booked - Country of Origin", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_booked_country_origin", read_only: true},
    ordln_po_booked_bol: {label: "PO Booked - BOL", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_booked_bol", read_only: true},
    ordln_po_booked_container_number: {label: "PO Booked - Container Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_booked_container_number", read_only: true},
    ordln_po_booked_seal_number: {label: "PO Booked - Seal Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_booked_seal_number", read_only: true},
    ordln_po_shipped_article: {label: "PO Shipped - Article Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_article", read_only: true},
    ordln_po_shipped_quantity: {label: "PO Shipped - Quantity", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_quantity", read_only: true},
    ordln_po_shipped_hts: {label: "PO Shipped - HTS", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_hts"}, read_only: true,
    ordln_po_shipped_price_per_unit: {label: "PO Shipped - Price / Unit", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_price_per_unit", read_only: true},
    ordln_po_shipped_total_price: {label: "PO Shipped - Total Price", data_type: :decimal, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_total_price", read_only: true},
    ordln_po_shipped_country_origin: {label: "PO Shipped - Country of Origin", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_country_origin", read_only: true},
    ordln_po_shipped_bol: {label: "PO Shipped - BOL", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_bol", read_only: true},
    ordln_po_shipped_container_number: {label: "PO Shipped - Container Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_container_number", read_only: true},
    ordln_po_shipped_seal_number: {label: "PO Shipped - Seal Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_po_shipped_seal_number", read_only: true},
    ordln_carb_statement: {label: "CARB Statement", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_carb_statement", read_only: true},
    ordln_patent_statement: {label: "Patent Statement", data_type: :string, module_type: "OrderLine", cdef_uid: "ordln_patent_statement", read_only: true},
    var_recipe: {label: 'Recipe', data_type: :text, module_type: 'Variant', cdef_uid: "var_recipe"},
    shp_booking_unlocked_date: {label: "Booking Unlocked Date", data_type: :date, module_type: "Shipment", cdef_uid: "shp_booking_unlocked_date"},
    shp_vgm_revised_date: {label: "VGM Revised Date", data_type: :datetime, module_type: "Shipment", cdef_uid: "shp_vgm_revised_date"},
    shp_vgm_revised_by: {label: "VGM Revised By", data_type: :integer, module_type: "Shipment", cdef_uid: "shp_vgm_revised_by", read_only: true, is_user: true},
    shp_factory_pack_revised_date: {label: "Factory Pack Revised Date", data_type: :datetime, module_type: "Shipment", cdef_uid: "shp_factory_pack_revised_date"},
    shp_factory_pack_revised_by: {label: "Factory Pack Revised By", data_type: :integer, module_type: "Shipment", cdef_uid: "shp_factory_pack_revised_by", read_only: true, is_user: true},
    shp_vgm_electronic_signature: {label: "VGM Electronic Signature", data_type: :string, module_type: "Shipment", cdef_uid: "shp_vgm_electronic_signature"},
    shp_vgm_signature_date: {label: "VGM Electronic Signature Date", data_type: :date, module_type: "Shipment", cdef_uid: "shp_vgm_signature_date"},
    shp_isf_revised_by: {label: "ISF Revised By", data_type: :integer, module_type: "Shipment", cdef_uid: "shp_isf_revised_by", read_only: true, is_user: true},
    shp_isf_revised_date: {label: "ISF Revised Date", data_type: :datetime, module_type: "Shipment", cdef_uid: "shp_isf_revised_date"},
    shp_testing_address: {label: "Testing Address", data_type: :integer, module_type: "Shipment", cdef_uid: "shp_testing_address", is_address: true},
    con_weighing_company: {label: "Weighing Company", data_type: :integer, module_type: "Container", cdef_uid: "con_weighing_company", is_address: true},
    con_weighed_date: {label: "Weighed Date", data_type: :date, module_type: "Container", cdef_uid: "con_weighed_date"},
    con_weighing_method: {label: "Weighing Method", data_type: :string, module_type: "Container", cdef_uid: "con_weighing_method"},
    con_cargo_weight: {label: "Cargo Weight", data_type: :decimal, module_type: "Container", cdef_uid: "con_cargo_weight"},
    con_dunnage_weight: {label: "Dunnage Weight", data_type: :decimal, module_type: "Container", cdef_uid: "con_dunnage_weight"},
    con_tare_weight: {label: "Tare Weight", data_type: :decimal, module_type: "Container", cdef_uid: "con_tare_weight"},
    con_total_vgm_weight: {label: "Total VGM Weight", data_type: :decimal, module_type: "Container", cdef_uid: "con_total_vgm_weight"},
    con_remarks: {label: "Remarks", data_type: :text, module_type: "Container", cdef_uid: "con_remarks"}
  }

  def self.included(base)
    base.extend(::OpenChain::CustomHandler::CustomDefinitionSupport)
    base.extend(ClassMethods)
  end

  module ClassMethods
    def prep_custom_definitions fields
      prep_custom_defs fields, CUSTOM_DEFINITION_INSTRUCTIONS
    end
  end
end; end; end; end
