development:
  :address: smtp.comcast.net
  :port: 587
  :authentication: plain
  :user_name: bglick231
  :password: soldpack
production:
  :address: smtp.comcast.net
  :port: 587
  :authentication: plain
  :user_name: bglick231
  :password: soldpack
