# This file contains settings relavent to connecting to the sql_proxy machine.
development:
  auth_token: test
  url: http://localhost:3001

test:
  auth_token: test
  url: http://localhost:3001

production:
  auth_token: GDK5XE0Q7lU6mZObPjVKS6FrHss=
  url: https://fenix-web-proxy.vfitrack.net
