development:
  server: testftp.chain.io
  user: testftp
  password: testftp999
  port: 10021
test:
  server: testftp.chain.io
  user: testftp
  password: testftp999
  port: 10021
production:
  server: ftp.chain.io
  user: chainroot
  password: czft9918#
