integration@vandegriftinc.com:
  client_id: 77914895035.apps.googleusercontent.com
  client_secret: SQsYhVwfebohOKHngD_sE12x
  refresh_token: 1/ROFzHoD6YppiobZQQRzbwx_dMw5OJdi6xQx3aWPpI0Q

integration-dev@vandegriftinc.com:
  client_id: 77914895035-kvh5fsht7v2rkvbrmf8m2r37bfmpack0.apps.googleusercontent.com
  client_secret: twHmvX9wz405C03zy9Z5PjcG
  refresh_token: 1/IjJ9g152fTfxiwVAVc7i7LilE11L5bznD8RftRyhV8A
