#!/usr/bin/env ruby
require 'fileutils'

APP_ROOT = File.expand_path('.', __dir__)

def system!(*args)
  system(*args) || abort("\n== Command #{args} failed ==")
end

FileUtils.chdir APP_ROOT do
  # This script is a way to setup or update your development environment automatically.
  # This script is idempotent, so that you can run it at anytime and get an expectable outcome.
  # Add necessary setup steps to this file.

  puts '== Installing dependencies =='
  system! 'gem install bundler -v 1.17.3 --conservative'
  system('bundle check') || system!('bundle install')

  puts "\n== Creating databases =="
  system! 'bundle exec rake db:create'
  system! 'bundle exec rake db:create RAILS_ENV=test'

  puts "\n== Migrating databases =="
  system! 'bundle exec rake db:migrate'
  system! 'bundle exec rake db:migrate RAILS_ENV=test'
end
