#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
require 'open_chain/tariff_finder'

f = File.open(ARGV[1],'w')
importers = Company.where(alliance_customer_number:['EDDIE','EBCC']).to_a
usa = Country.find_by_iso_code('US')
tf = OpenChain::TariffFinder.new(usa,importers)
cursor = 0
CSV.foreach(ARGV[0],col_sep:'|') do |row|
	cursor += 1
	style = row[5].strip
  coo = row[4].strip
  r = tf.find_by_style style, coo
	if r 
		f << (row + [r.mid,r.hts_code]).to_csv
	else
		f << (row + ['','']).to_csv
	end
	puts cursor
end
f.close
