#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))

def wd opts = {}
  {run_monday: true, run_tuesday: true, run_wednesday: true, run_thursday: true, run_friday: true, run_saturday: true, run_sunday: true}.merge opts
end

# Ensure the integration account exists
integration = User.integration

 SchedulableJob.create_default_jobs!