#!/usr/bin/env ruby

require File.expand_path(File.join(File.dirname(__FILE__), '..', 'config', 'environment'))
f = File.open('tmp/jcrew_canada_out.csv','w')
cursor = 0
CSV.foreach('tmp/jcrew_canada_in.csv') do |row|
	cursor += 1
	if cursor == 1 
		f << (row + ["MID","HTS"]).to_csv
		next
	end
	style = row[4]
	cil = CommercialInvoiceTariff.joins(:commercial_invoice_line=>{:commercial_invoice=>:entry}).
		where("entries.customer_number IN ('J0000','JCREW')").
		where("commercial_invoice_lines.part_number = ?",style).
		order("entries.release_date DESC").first
	if cil
		f << (row + [cil.commercial_invoice_line.commercial_invoice.mfid,cil.hts_code]).to_csv
	else
		f << (row + ['','']).to_csv
	end
	puts cursor
end
f.close
