class LLTicket
  def initialize
    @integration = User.integration
  end
  def run
    company_names = ["ALL GLOBE INC","ARMSTRONG WORLD INDUSTRIES CANADA L","PG HARDWOOD FLOORING INC",
      "UNIBOARD CANADA INC","AKZENTA VERTRIEBS GMBH","AMORIM FLOORING NA INC","ANATOLIA TILE AND STONE","KAINDL FLOORING GMBH",
      "KRONOTEX GMBH & CO KG","MERCURY CERAMICA","PORCELAINGRES GMBH","SERENISSIMA CIR INDUSTRIE CERAMICHE","ALFAGRES",
      "AMERICAN HARDWOOD INDUSTRIES LLC","ARMSTRONG WORLD INDUSTRIES INC","BAJA INC","BEASLEY FLOORING PRODUCTS INC","Bellawood Production",
      "BERRY PLASTICS CORPORATION","BLC HARDWOOD FLOORING LLC","BOSTIK INC","CAL-FLOR ACCESSORY SYSTEMS","CAPITAL FOREST",
      "CLARION LAMINATES LLC","DAP INC","DELTA HARDWOOD FLOORING INC","DTA USA GROUP INC","DYNARIC INC.","EMIL AMERICA INC","FANGYUAN LOLA CERAMICS INC",
      "FINI NUAIR SPA","FOAM PRODUCTS CORPORATION","FRAMERICA","FROM THE FOREST LLC","GRILLWORKS, INC.","HARDWOOD TRANSFORMATIONS INC","IDEAL STAIR PARTS",
      "ILVA","KEENE BUILDING PRODUCTS","KENNEBEC LUMBER COMPANY INC","LIGNOMAT USA","MACON HARDWOOD LLC","MANNINGTON MILLS INC","MAPEI CORPORATION",
      "MARLIN LUMBER SALES","MASA CORPORATION","METRIE INC","MK DIAMOND PRODUCTS INC","MOLEEM US HOLDINGS CORP","MOTION INDUSTRIES INC","MP GLOBAL PRODUCTS, LLC",
      "MULLICAN FLOORING LP","PAMESA DE BRASIL","PENNWOOD PRODUCTS, INC.","PENNWOOD PRODUCTS, INC.","PREMIER HARDWOOD PRODUCTS, INC","PRIME GLOBAL PRODUCTS INC",
      "Q.E.P. CO. INC.","ROPPE CORPORATION","SEABOARD INTERNATIONAL","SHAW INDUSTRIES INC","STAIRTEK","STANLEY BLACK & DECKER","SWISS KRONO LLC","TAYLOR TOOLS INC",
      "TROUT RIVER DRY KILNS LLC","TROUT RIVER LUMBER, LLC","VERSATRIM, INC. A/C#204995"]
    Company.where("name in (?)",company_names).each do |vend|
      vend.vendor_orders.where('closed_at is not null').where(accepted_by_id:nil).each do |o|
        o.accept! @integration
      end
    end
  end
end
