require 'open_chain/custom_handler/custom_definition_support'
module OpenChain
  module CustomHandler
    module Polo
      module PoloCustomDefinitionSupport
        extend ActiveSupport::Concern

        CUSTOM_DEFINITION_INSTRUCTIONS = {
          :ord_division => {label: "Merchandise Division", data_type: :string, module_type: "Order", cdef_uid: "ord_division"},
          :ord_line_ex_factory_date => {label: "Planned Ex-Factory", data_type: :date, module_type: "OrderLine", cdef_uid: "ord_line_ex_factory_date"},
          :ord_line_ship_mode => {label: "Ship Mode", data_type: :string, module_type: "OrderLine", cdef_uid: "ord_line_ship_mode"},
          :ord_line_board_number => {label: "Board Number", data_type: :string, module_type: "OrderLine", cdef_uid: "ord_line_board_number"},
          :bartho_customer_id=>{:label=>"Barthco Customer ID", :data_type=>:string, :module_type=>'Product', cdef_uid: "prod_barthco_customer_id"},
          :season=>{:label=>"Season", :data_type => :string, :module_type=>'Product', cdef_uid: "prod_season"},
          :test_style=>{:label=>"Test Style", :data_type=>:string, :module_type=>'Product', cdef_uid: "prod_test_style"},
          :set_type=>{:label=>"Set Type", :data_type=>:string, :module_type=>'Classification', cdef_uid: "class_set_type"},
          :merch_division=>{:label=>'Merch Div Desc', :data_type=>:string, :module_type=>'Product', cdef_uid: "prod_merch_division"},
          :csm_numbers => {:label=>'CSM Number', :data_type=>:text, :module_type=>'Product', cdef_uid: "prod_csm_numbers"},
          :fiber_content => {:label=>'Fiber Content %s', :data_type=>:string, :module_type=>'Product', cdef_uid: "prod_fiber_content"},
          :fabric_type_1 => {label: 'Fabric Type - 1', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_1"},
          :fabric_1 => {label: 'Fabric - 1', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_1"},
          :fabric_percent_1 => {label: 'Fabric % - 1', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_1"},
          :fabric_type_2 => {label: 'Fabric Type - 2', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_2"},
          :fabric_2 => {label: 'Fabric - 2', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_2"},
          :fabric_percent_2 => {label: 'Fabric % - 2', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_2"},
          :fabric_type_3 => {label: 'Fabric Type - 3', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_3"},
          :fabric_3 => {label: 'Fabric - 3', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_3"},
          :fabric_percent_3 => {label: 'Fabric % - 3', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_3"},
          :fabric_type_4 => {label: 'Fabric Type - 4', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_4"},
          :fabric_4 => {label: 'Fabric - 4', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_4"},
          :fabric_percent_4 => {label: 'Fabric % - 4', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_4"},
          :fabric_type_5 => {label: 'Fabric Type - 5', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_5"},
          :fabric_5 => {label: 'Fabric - 5', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_5"},
          :fabric_percent_5 => {label: 'Fabric % - 5', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_5"},
          :fabric_type_6 => {label: 'Fabric Type - 6', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_6"},
          :fabric_6 => {label: 'Fabric - 6', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_6"},
          :fabric_percent_6 => {label: 'Fabric % - 6', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_6"},
          :fabric_type_7 => {label: 'Fabric Type - 7', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_7"},
          :fabric_7 => {label: 'Fabric - 7', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_7"},
          :fabric_percent_7 => {label: 'Fabric % - 7', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_7"},
          :fabric_type_8 => {label: 'Fabric Type - 8', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_8"},
          :fabric_8 => {label: 'Fabric - 8', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_8"},
          :fabric_percent_8 => {label: 'Fabric % - 8', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_8"},
          :fabric_type_9 => {label: 'Fabric Type - 9', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_9"},
          :fabric_9 => {label: 'Fabric - 9', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_9"},
          :fabric_percent_9 => {label: 'Fabric % - 9', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_9"},
          :fabric_type_10 => {label: 'Fabric Type - 10', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_10"},
          :fabric_10 => {label: 'Fabric - 10', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_10"},
          :fabric_percent_10 => {label: 'Fabric % - 10', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_10"},
          :fabric_type_11 => {label: 'Fabric Type - 11', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_11"},
          :fabric_11 => {label: 'Fabric - 11', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_11"},
          :fabric_percent_11 => {label: 'Fabric % - 11', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_11"},
          :fabric_type_12 => {label: 'Fabric Type - 12', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_12"},
          :fabric_12 => {label: 'Fabric - 12', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_12"},
          :fabric_percent_12 => {label: 'Fabric % - 12', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_12"},
          :fabric_type_13 => {label: 'Fabric Type - 13', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_13"},
          :fabric_13 => {label: 'Fabric - 13', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_13"},
          :fabric_percent_13 => {label: 'Fabric % - 13', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_13"},
          :fabric_type_14 => {label: 'Fabric Type - 14', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_14"},
          :fabric_14 => {label: 'Fabric - 14', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_14"},
          :fabric_percent_14 => {label: 'Fabric % - 14', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_14"},
          :fabric_type_15 => {label: 'Fabric Type - 15', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_type_15"},
          :fabric_15 => {label: 'Fabric - 15', data_type: :string, module_type: "Product", cdef_uid: "prod_fabric_15"},
          :fabric_percent_15 => {label: 'Fabric % - 15', data_type: :decimal, module_type: "Product", cdef_uid: "prod_fabric_percent_15"},
          :clean_fiber_content => {label: 'Clean Fiber Content', data_type: :string, module_type: "Product", read_only: true, cdef_uid: "prod_clean_fiber_content"},
          :msl_fiber_failure => {label: "MSL Fiber Failure", data_type: :boolean, module_type: "Product", cdef_uid: "prod_msl_fiber_failure"},
          :length_cm => {label: "Length (cm)", data_type: :decimal, module_type: "Product", cdef_uid: "prod_length_cm"},
          :width_cm => {label: "Width (cm)", data_type: :decimal, module_type: "Product", cdef_uid: "prod_width_cm"},
          :height_cm => {label: "Height (cm)", data_type: :decimal, module_type: "Product", cdef_uid: "prod_height_cm"},
          :msl_receive_date => {label: "MSL+ Receive Date", data_type: :date, module_type: "Product", cdef_uid: "prod_msl_receive_date"},
          :msl_us_class => {label: "MSL+ US Class", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_us_class"},
          :msl_us_brand => {label: "MSL+ US Brand", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_us_brand"},
          :msl_us_sub_brand => {label: "MSL+ US Sub Brand", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_us_sub_brand"},
          :msl_model_desc => {label: "MSL+ Model Description", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_model_desc"},
          :msl_hts_desc => {label: "MSL+ HTS Description", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_hts_desc"},
          :msl_hts_desc_2 => {label: "MSL+ HTS Description 2", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_hts_desc_2"},
          :msl_hts_desc_3 => {label: "MSL+ HTS Description 3", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_hts_desc_3"},
          :ax_subclass => {label: "AX Subclass", data_type: :string, module_type: "Product", cdef_uid: "prod_ax_subclass"},
          :msl_item_desc => {label: "MSL+ Item Description", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_item_desc"},
          :msl_us_season => {label: "MSL+ US Season", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_us_season"},
          :msl_gcc_desc => {label: "GCC Description", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_gcc_desc"},
          :msl_board_number => {label: "Board Number", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_board_number"},
          :common_name_1 => {label: "Common Name 1", data_type: :string, module_type: "Product", cdef_uid: "prod_common_name_1"},
          :common_name_2 => {label: "Common Name 2", data_type: :string, module_type: "Product", cdef_uid: "prod_common_name_2"},
          :common_name_3 => {label: "Common Name 3", data_type: :string, module_type: "Product", cdef_uid: "prod_common_name_3"},
          :common_name_4 => {label: "Common Name 4", data_type: :string, module_type: "Product", cdef_uid: "prod_common_name_4"},
          :common_name_5 => {label: "Common Name 5", data_type: :string, module_type: "Product", cdef_uid: "prod_common_name_5"},
          :scientific_name_1 => {label: "Scientific Name 1", data_type: :string, module_type: "Product", cdef_uid: "prod_scientific_name_1"},
          :scientific_name_2 => {label: "Scientific Name 2", data_type: :string, module_type: "Product", cdef_uid: "prod_scientific_name_2"},
          :scientific_name_3 => {label: "Scientific Name 3", data_type: :string, module_type: "Product", cdef_uid: "prod_scientific_name_3"},
          :scientific_name_4 => {label: "Scientific Name 4", data_type: :string, module_type: "Product", cdef_uid: "prod_scientific_name_4"},
          :scientific_name_5 => {label: "Scientific Name 5", data_type: :string, module_type: "Product", cdef_uid: "prod_scientific_name_5"},
          :fish_wildlife_origin_1 => {label: "F&W Origin 1", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_origin_1"},
          :fish_wildlife_origin_2 => {label: "F&W Origin 2", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_origin_2"},
          :fish_wildlife_origin_3 => {label: "F&W Origin 3", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_origin_3"},
          :fish_wildlife_origin_4 => {label: "F&W Origin 4", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_origin_4"},
          :fish_wildlife_origin_5 => {label: "F&W Origin 5", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_origin_5"},
          :fish_wildlife_source_1 => {label: "F&W Source 1", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_source_1"},
          :fish_wildlife_source_2 => {label: "F&W Source 2", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_source_2"},
          :fish_wildlife_source_3 => {label: "F&W Source 3", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_source_3"},
          :fish_wildlife_source_4 => {label: "F&W Source 4", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_source_4"},
          :fish_wildlife_source_5 => {label: "F&W Source 5", data_type: :string, module_type: "Product", cdef_uid: "prod_fish_wildlife_source_5"},
          :origin_wildlife => {label: "Origin of Wildlife", data_type: :string, module_type: "Product", cdef_uid: "prod_origin_wildlife"},
          :semi_precious => {label: "Semi-Precious", data_type: :boolean, module_type: "Product", cdef_uid: "prod_semi_precious"},
          :semi_precious_type => {label: "Type of Semi-Precious", data_type: :string, module_type: "Product", cdef_uid: "prod_semi_precious_type"},
          :cites => {label: "CITES", data_type: :boolean, module_type: "Product", cdef_uid: "prod_cites"},
          :fish_wildlife => {label: "Fish & Wildlife", data_type: :boolean, module_type: "Product", cdef_uid: "prod_fish_wildlife"},
          :msl_fiber_status => {label: "MSL Fiber Status", data_type: :string, module_type: "Product", cdef_uid: "prod_msl_fiber_status"},
          :product_area => {label: "Product Area", data_type: :string, module_type: "Product", cdef_uid: "prod_product_area"},
          :prod_fda_indicator => {label: "US FDA Indicator", data_type: :string, module_type: "Product", cdef_uid: "prod_fda_indicator"},
          :long_description => {label: "Long Description", data_type: :text, module_type: "Product", cdef_uid: "prod_long_description"},
          :stitch_count_vertical => {label: "Stitch Count / 2cm Vertical", data_type: :string, module_type: "Product", cdef_uid: "prod_stitch_count_vertical"},
          :stitch_count_horizontal => {label: "Stitch Count / 2cm Horizontal", data_type: :string, module_type: "Product", cdef_uid: "prod_stitch_count_horizontal"},
          :grams_square_meter => {label: "Grams / Square Meter", data_type: :string, module_type: "Product", cdef_uid: "prod_grams_square_meter"},
          :knit_type => {label: "Knit Type (Jersey, mesh, etc)", data_type: :string, module_type: "Product", cdef_uid: "prod_knit_type"},
          :type_of_bottom => {label: "Type of Bottom (Hemmed, ribbed,etc)", data_type: :string, module_type: "Product", cdef_uid: "prod_type_of_bottom"},
          :functional_neck_closure => {label: "Functional Neck Closure", data_type: :boolean, module_type: "Product", cdef_uid: "prod_functional_neck_closure"},
          :significantly_napped => {label: "Significantly Napped", data_type: :boolean, module_type: "Product", cdef_uid: "prod_significantly_napped"},
          :back_type => {label: "Back Type / Shape", data_type: :string, module_type: "Product", cdef_uid: "prod_back_type"},
          :defined_armholes => {label: "Defined Armholes", data_type: :boolean, module_type: "Product", cdef_uid: "prod_defined_armholes"},
          :strap_width => {label: "Strap Width (in.)", data_type: :string, module_type: "Product", cdef_uid: "prod_strap_width"},
          :pass_water_resistant_test => {label: "Pass Water Resistant Test AATC35-2006", data_type: :string, module_type: "Product", cdef_uid: "prod_pass_water_resistant_test"},
          :type_of_coating => {label: "Type of Coating", data_type: :string, module_type: "Product", cdef_uid: "prod_type_of_coating"},
          :padding_or_filling => {label: "Padding or Filling?", data_type: :string, module_type: "Product", cdef_uid: "prod_padding_or_filling"},
          :meets_down_requirments => {label: "Meets Down Requirements", data_type: :boolean, module_type: "Product", cdef_uid: "prod_meets_down_requirments"},
          :tightening_at_waist => {label: "Tightening at Waist (Cord, Ribbing, etc)", data_type: :string, module_type: "Product", cdef_uid: "prod_tightening_at_waist"},
          :denim => {label: "Denim", data_type: :string, module_type: "Product", cdef_uid: "prod_denim"},
          :denim_color => {label: "Denim color", data_type: :string, module_type: "Product", cdef_uid: "prod_denim_color"},
          :corduroy => {label: "Corduroy", data_type: :boolean, module_type: "Product", cdef_uid: "prod_corduroy"},
          :shearling => {label: "Shearling", data_type: :boolean, module_type: "Product", cdef_uid: "prod_shearling"},
          :total_back_panels => {label: "Total # of Back Panels", data_type: :integer, module_type: "Product", cdef_uid: "prod_total_back_panels"},
          :short_fall_above_knee => {label: "Short Fall Above Knee", data_type: :boolean, module_type: "Product", cdef_uid: "prod_short_fall_above_knee"},
          :mesh_lining => {label: "Mesh Lining", data_type: :boolean, module_type: "Product", cdef_uid: "prod_mesh_lining"},
          :full_elastic_waistband => {label: "Full Elastic Waistband", data_type: :boolean, module_type: "Product", cdef_uid: "prod_full_elastic_waistband"},
          :full_functional_drawstring => {label: "Full Functional Drawstring", data_type: :boolean, module_type: "Product", cdef_uid: "prod_full_functional_drawstring"},
          :cover_crown_of_head => {label: "Cover Crown Of Head", data_type: :boolean, module_type: "Product", cdef_uid: "prod_cover_crown_of_head"},
          :wholly_or_partially_braid => {label: "Wholly or Partially Braid", data_type: :string, module_type: "Product", cdef_uid: "prod_wholly_or_partially_braid"},
          :yarn_dyed => {label: "Yarn Dyed", data_type: :string, module_type: "Product", cdef_uid: "prod_yarn_dyed"},
          :colors_in_warp_weft => {label: "# of Colors in Warp / Weft", data_type: :string, module_type: "Product", cdef_uid: "prod_colors_in_warp_weft"},
          :piece_dyed => {label: "Piece Dyed", data_type: :boolean, module_type: "Product", cdef_uid: "prod_piece_dyed"},
          :printed => {label: "Printed", data_type: :boolean, module_type: "Product", cdef_uid: "prod_printed"},
          :solid => {label: "Solid", data_type: :boolean, module_type: "Product", cdef_uid: "prod_solid"},
          :ounces_sq_yd => {label: "Ounces / Sq Yd", data_type: :decimal, module_type: "Product", cdef_uid: "prod_ounces_sq_yd"},
          :size_scale => {label: "Size Scale (S/M/L or 15/16/17)", data_type: :string, module_type: "Product", cdef_uid: "prod_size_scale"},
          :type_of_fabric => {label: "Type of Fabric (velour, velvet, etc)", data_type: :string, module_type: "Product", cdef_uid: "prod_type_of_fabric"},
          :weight_of_fabric => {label: "Weight of Fabric", data_type: :string, module_type: "Product", cdef_uid: "prod_weight_of_fabric"},
          :form_fitting_or_loose_fitting => {label: "Form Fitting or Loose Fitting", data_type: :string, module_type: "Product", cdef_uid: "prod_form_fitting_or_loose_fitting"},
          :functional_open_fly => {label: "Functional Open Fly", data_type: :boolean, module_type: "Product", cdef_uid: "prod_functional_open_fly"},
          :fly_covered => {label: "Fly Covered With Open Placket", data_type: :boolean, module_type: "Product", cdef_uid: "prod_fly_covered"},
          :tightening_at_cuffs => {label: "Tightening At Cuffs", data_type: :boolean, module_type: "Product", cdef_uid: "prod_tightening_at_cuffs"},
          :embellishments_or_ornamentation => {label: "Embellishments or Ornamentation", data_type: :boolean, module_type: "Product", cdef_uid: "prod_embellishments_or_ornamentation"},
          :sizing => {label: "Sizing", data_type: :string, module_type: "Product", cdef_uid: "prod_sizing"},
          :sold_in_sleepwear_dept => {label: "Sold In Sleepwear Dept.", data_type: :boolean, module_type: "Product", cdef_uid: "prod_sold_in_sleepwear_dept"},
          :pcs_in_set => {label: "# pcs. in set", data_type: :integer, module_type: "Product", cdef_uid: "prod_pcs_in_set"},
          :sold_as_set => {label: "If more than 1 pc, sold as set?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_sold_as_set"},
          :footwear_upper => {label: "Footwear Upper", data_type: :string, module_type: "Product", cdef_uid: "prod_footwear_upper"},
          :footwear_outsole => {label: "Footwear Outsole", data_type: :string, module_type: "Product", cdef_uid: "prod_footwear_outsole"},
          :welted => {label: "Welted", data_type: :boolean, module_type: "Product", cdef_uid: "prod_welted"},
          :cover_the_ankle => {label: "Does it completely cover the ankle?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_cover_the_ankle"},
          :secure_closure => {label: "Secure Closure", data_type: :boolean, module_type: "Product", cdef_uid: "prod_secure_closure"},
          :closure_type => {label: "Closure Type", data_type: :string, module_type: "Product", cdef_uid: "prod_closure_type"},
          :multiple_compartment => {label: "Multiple Compartment", data_type: :boolean, module_type: "Product", cdef_uid: "prod_multiple_compartment"},
          :fourchettes_for_gloves => {label: "Fourchettes for Gloves", data_type: :boolean, module_type: "Product", cdef_uid: "prod_fourchettes_for_gloves"},
          :lined_for_gloves => {label: "Lined for Gloves", data_type: :boolean, module_type: "Product", cdef_uid: "prod_lined_for_gloves"},
          :seamed => {label: "Seamed", data_type: :boolean, module_type: "Product", cdef_uid: "prod_seamed"},
          :components => {label: "Components", data_type: :string, module_type: "Product", cdef_uid: "prod_components"},
          :cost_of_component => {label: "Cost of Component", data_type: :string, module_type: "Product", cdef_uid: "prod_cost_of_component"},
          :weight_of_components => {label: "Weight of Components", data_type: :string, module_type: "Product", cdef_uid: "prod_weight_of_components"},
          :material_content_of_posts_earrings => {label: "Material Content of Posts - Earrings", data_type: :string, module_type: "Product", cdef_uid: "prod_material_content_of_posts_earrings"},
          :filled => {label: "Filled", data_type: :boolean, module_type: "Product", cdef_uid: "prod_filled"},
          :type_of_fill => {label: "Type of Fill", data_type: :string, module_type: "Product", cdef_uid: "prod_type_of_fill"},
          :coated => {label: "Is the fabric coated?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_coated"},
          :telescopic_shaft => {label: "Telescopic Shaft", data_type: :boolean, module_type: "Product", cdef_uid: "prod_telescopic_shaft"},
          :unit_price => {label: "Unit Price", data_type: :decimal, module_type: "Product", cdef_uid: "prod_unit_price"},
          :vendor_code => {label: "Vendor Code", data_type: :string, module_type: "Product", cdef_uid: "prod_vendor_code"},
          :country_of_origin => {label: "Country of Origin", data_type: :string, module_type: "Product", cdef_uid: "prod_country_of_origin"},
          :common_name_fw => {label: "Common Name (F&W)", data_type: :string, module_type: "Product", cdef_uid: "prod_common_name_fw"},
          :scientific_name => {label: "Scientific Name", data_type: :string, module_type: "Product", cdef_uid: "prod_scientific_name"},
          :source_indicator => {label: "Source Indicator", data_type: :string, module_type: "Product", cdef_uid: "prod_source_indicator"},
          :royalty_percentage => {label: "Royalty %", data_type: :decimal, module_type: "Product", cdef_uid: "prod_royalty_percentage"},
          :binding_ruling_number => {label: "Binding Ruling Number", data_type: :string, module_type: "Classification", cdef_uid: "class_binding_ruling_number"},
          :binding_ruling_type => {label: "Binding Ruling Type", data_type: :string, module_type: "Classification", cdef_uid: "class_binding_ruling_type"},
          :mid => {label: "MID", data_type: :string, module_type: "Classification", cdef_uid: "class_mid"},
          :fda_product_code => {label: "FDA Product Code", data_type: :string, module_type: "Classification", cdef_uid: "class_fda_product_code"},
          :effective_date => {label: "Effective Date", data_type: :date, module_type: "Product", cdef_uid: "prod_effective_date"},
          :price_uom => {label: "Price UOM", data_type: :string, module_type: "Product", cdef_uid: "prod_price_uom"},
          :special_program_indicator => {label: "Special Program Indicator", data_type: :string, module_type: "Classification", cdef_uid: "class_spi"},
          :cvd_case => {label: "CVD Case #", data_type: :string, module_type: "Classification", cdef_uid: "class_cvd_case"},
          :add_case => {label: "ADD Case #", data_type: :string, module_type: "Classification", cdef_uid: "class_add_case"},
          :ptp_code => {label: "PTP Code", data_type: :string, module_type: "Product", cdef_uid: "prod_ptp_code"},
          :terms_of_sale => {label: "Terms of Sale", data_type: :string, module_type: "Product", cdef_uid: "prod_terms_of_sale"},
          :worsted_wool => {label: "Worsted Wool", data_type: :boolean, module_type: "Product", cdef_uid: "prod_worsted_wool"},
          :microns => {label: "# of Microns", data_type: :string, module_type: "Product", cdef_uid: "prod_microns"},
          :infant_diaper_cover => {label: "Infant Diaper Cover", data_type: :boolean, module_type: "Product", cdef_uid: "prod_infant_diaper_cover"},
          :lining => {label: "Lining", data_type: :string, module_type: "Product", cdef_uid: "prod_lining"},
          :trim => {label: "Trim", data_type: :string, module_type: "Product", cdef_uid: "prod_trim"},
          :lin_number => {label: "LIN Number", data_type: :string, module_type: "Product", cdef_uid: "prod_lin_number"},
          :chart_comments => {label: "Chart Comments", data_type: :text, module_type: "Product", cdef_uid: "prod_chart_comments"},
          :measurement_per_single_yarn => {label: "Measurement per single yarn < 67 decitex", data_type: :string, module_type: "Product", cdef_uid: "prod_measurement_per_single_yarn"},
          :peaked_caps => {label: "Peaked caps", data_type: :string, module_type: "Product", cdef_uid: "prod_peaked_caps"},
          :weight_per_garment => {label: "Weight per Garment > 1kg?", data_type: :string, module_type: "Product", cdef_uid: "prod_weight_per_garment"},
          :knee_length_stockings => {label: "Knee Length Stockings?", data_type: :string, module_type: "Product", cdef_uid: "prod_knee_length_stockings"},
          :country_description => {label: "Country Description", data_type: :text, module_type: "Classification", cdef_uid: "class_country_description"},
          :digit_style_9 => {label: "9 Digit Style No. ", data_type: :string, module_type: "Product", cdef_uid: "prod_digit_style_9"},
          :digit_style_6 => {label: "6 Digit Style No.", data_type: :string, module_type: "Product", cdef_uid: "prod_digit_style_6"},
          :factory_name => {label: "Factory Name", data_type: :text, module_type: "Product", cdef_uid: "prod_factory_name"},
          :production_manager => {label: "Production Manager", data_type: :string, module_type: "Product", cdef_uid: "prod_production_manager"},
          :eu_approved => {label: "EU Approved", data_type: :string, module_type: "Product", cdef_uid: "prod_eu_approved"},
          :pillowcase => {label: "Is it a Pillowcase?", data_type: :string, module_type: "Product", cdef_uid: "prod_pillowcase"},
          :pillowcover => {label: "Is it a Pillowcover?", data_type: :string, module_type: "Product", cdef_uid: "prod_pillowcover"},
          :pillow => {label: "Is it a Pillow?", data_type: :string, module_type: "Product", cdef_uid: "prod_pillow"},
          :content_for_filling_of_pillow => {label: "Content for filling of Pillow", data_type: :text, module_type: "Product", cdef_uid: "prod_content_for_filling_of_pillow"},
          :bolster_case => {label: "Is it a bolster case?", data_type: :string, module_type: "Product", cdef_uid: "prod_bolster_case"},
          :napped => {label: "Is it napped?", data_type: :string, module_type: "Product", cdef_uid: "prod_napped"},
          # Yes, they have two different types of fields to determine if a product is printed...awesome
          :is_it_printed => {label: "Is it printed?", data_type: :string, module_type: "Product", cdef_uid: "prod_is_it_printed"},
          :embroidered => {label: "Does it contain any embro., lace, braid, edging, trim, piping or applique?", data_type: :string, module_type: "Product", cdef_uid: "prod_embroidered"},
          :quilted => {label: "Is it quilted?", data_type: :string, module_type: "Product", cdef_uid: "prod_quilted"},
          :piping_exceed => {label: "Does piping exceed 6.35mm?", data_type: :string, module_type: "Product", cdef_uid: "prod_piping_exceed"},
          :silk_gt_50 => {label: "Is silk =>50% by wt. incl. lining of tie?", data_type: :string, module_type: "Product", cdef_uid: "prod_silk_gt_50"},
          :sunglasses => {label: "Sunglasses", data_type: :string, module_type: "Product", cdef_uid: "prod_sunglasses"},
          :fws_3177 => {label: "FWS 3177", data_type: :string, module_type: "Product", cdef_uid: "prod_fws_3177"},
          :sap_brand => {label: "SAP Brand", data_type: :boolean, module_type: "Product", cdef_uid: "prod_sap_brand"},
          :csm_department => {label: "CSM Department", data_type: :string, module_type: "Product", cdef_uid: "prod_csm_department"},
          :csm_season => {label: "CSM Season", data_type: :text, module_type: "Product", cdef_uid: "prod_csm_season"},
          :csm_received_date_first => {label: "CSM Received Date (First)", data_type: :date, module_type: "Product", cdef_uid: "prod_csm_received_date_first"},
          :csm_received_date_last => {label: "CSM Received Date (Last)", data_type: :date, module_type: "Product", cdef_uid: "prod_csm_received_date_last"},
          :knotted => {label: "Is it Knotted?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_knotted"},
          :woven => {label: "Is it woven incl. Schumacks, Karamanie, Kelem or sim. hand woven rugs?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_woven"},
          :tufted => {label: "Is it tufted?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_tufted"},
          :area_measurement => {label: "Is the area measurement < 5.25 square meters?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_area_measurement"},
          :felt => {label: "Is it made of felt?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_felt"},
          :coir => {label: "Is it made of coir?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_coir"},
          :needlepoint => {label: "Is it made from needlepoint?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_needlepoint"},
          :gender_desc => {label: "RL Gender Description", data_type: :string, module_type: "Product", cdef_uid: "prod_rl_gender_description"},
          :suffix_indicator => {label: "Suffix Indicator", data_type: :string, module_type: "Product", cdef_uid: "prod_suffix_indicator"},
          :exception_code => {label: "Exception Code", data_type: :string, module_type: "Product", cdef_uid: "prod_exception_code"},
          :suffix => {label: "Suffix", data_type: :string, module_type: "Product", cdef_uid: "prod_suffix"},
          :comments => {label: "Comments", data_type: :text, module_type: "Product", cdef_uid: "prod_comments"},
          :part_number => {label: "Part Number", data_type: :string, module_type: "Product", cdef_uid: "prod_part_number"},
          :cover_the_calf => {label: "Does it cover the calf ? ", data_type: :boolean, module_type: "Product", cdef_uid: "prod_cover_the_calf"},
          :vamp_made_of_straps => {label: "Is vamp made of straps of which has one or several pieces cut out? ", data_type: :boolean, module_type: "Product", cdef_uid: "prod_vamp_made_of_straps"},
          :height_gt_3_cm => {label: "With the sole and heel combined have a height of more than 3 cm.?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_height_gt_3_cm"},
          :platform_of_wood => {label: "Is it made on a base or platform of wood or cork?", data_type: :string, module_type: "Product", cdef_uid: "prod_platform_of_wood"},
          :inner_sole => {label: "Does it have an inner sole?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_inner_sole"},
          :protective_metal_toe_cap => {label: "Does it have a protective metal toe cap?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_protective_metal_toe_cap"},
          :upper_leather_straps => {label: "Does the upper consist of leather straps across the instep and around the big toe?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_upper_leather_straps"},
          :turned_footwear => {label: "Is it turned footwear?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_turned_footwear"},
          :test_required => {label: "Test Required", data_type: :boolean, module_type: "Product", cdef_uid: "prod_test_required"},
          :cover_the_knee => {label: "Does it cover the knee?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_cover_the_knee"},
          :footwear_waterproof => {label: "Is the footwear waterproof?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_footwear_waterproof"},
          :footwear_lined_with_textile => {label: "Is the footwear lined with textile fabric?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_footwear_lined_with_textile"},
          :uppers_gt_90_esau => {label: "Does the footwear have uppers of which 90% of the ESAU (including accessories/reinforcements rubber/plastic? ", data_type: :boolean, module_type: "Product", cdef_uid: "prod_uppers_gt_90_esau"},
          :zoris => {label: "Does it have a Zoris? ", data_type: :boolean, module_type: "Product", cdef_uid: "prod_zoris"},
          :open_toes => {label: "Open toes or open heels?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_open_toes"},
          :slip_on_type => {label: "Slip on type that is held to the foot without use of laces, buckles or other fasteners?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_slip_on_type"},
          :protection_against_water => {label: "Does it provide protection against water or cold/inclement weather?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_protection_against_water"},
          :one_piece_by_molding => {label: "For sandals and similar footwear of plastics, is it produced in one piece by molding?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_one_piece_by_molding"},
          :foxing => {label: "Foxing?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_foxing"},
          :weight_of_rubber_plastic_lt_10 => {label: "Is the weight of the rubber/plastic less than 10% of the entire shoe?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_weight_of_rubber_plastic_lt_10"},
          :rubber_plastic_soles => {label: "Does it have rubber/plastic soles which are affixed to the upper exclusively with an adhesive?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_rubber_plastic_soles"},
          :weight_of_rubber_plastic_lt50 => {label: "Is the weight of the rubber, plastic and textile less than 50% of the entire shoe?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_weight_of_rubber_plastic_lt50"},
          :uppers_gt_50_esau => {label: "Does the footwear have uppers of which over 50% of the ESAU including leather accessories/reinforcements is leather?", data_type: :boolean, module_type: "Product", cdef_uid: "prod_uppers_gt_50_esau"},
          :vendor_name => {label: "Vendor Name", data_type: :string, module_type: "Product", cdef_uid: "prod_vendor_name"},
          :ic_number => {label: "IC #", data_type: :string, module_type: "Product", cdef_uid: "prod_ic_number"},
          :licensee_product => {label: "Licensee Product", data_type: :boolean, module_type: "Product", cdef_uid: "prod_licensee_product"},
          :num_of_sides_fringes => {label: "# of sides (fringes)", data_type: :string, module_type: "Product", cdef_uid: "prod_num_of_sides_fringes"},
          :functional_or_decorative => {label: "Functional or Decorative", data_type: :string, module_type: "Product", cdef_uid: "prod_functional_or_decorative"},
          :flanelle_percale => {label: "Flanelle, Percale or Other", data_type: :string, module_type: "Product", cdef_uid: "prod_flanelle_percale"},
          # This knit_woven field is a replacement for the old "Knit / Woven?" field.  The old "Knit / Woven?" field became "Material Group (Deprecated)"
          :knit_woven => {label: "Knit / Woven", data_type: :string, module_type: "Product", cdef_uid: "prod_knit_woven"},
          :material_group => {label: "Material Group (Deprecated)", data_type: :string, module_type: "Product", cdef_uid: "prod_material_group"},
          :allocation_category => {label: "Allocation Category", data_type: :string, module_type: "Product", cdef_uid: "prod_allocation_category"},
          :merchandising_fabrication => {label: "Merchandising Fabrication", data_type: :string, module_type: "Product", cdef_uid: "prod_merchandising_fabrication"},
          :product_class_description => {label: "Product Class Description", data_type: :string, module_type: "Product", cdef_uid: "prod_product_class_description"},
          :material_status => {label: "Material Status", data_type: :string, module_type: "Product", read_only: true, cdef_uid: "prod_material_status"},
          :ax_export_status => {label: "AX Export Status", data_type: :string, module_type: "Product", read_only: true, cdef_uid: "prod_ax_export_status"},
          :ax_export_status_manual => {label: "AX Export Status-Manual", data_type: :string, module_type: "Product", cdef_uid: "prod_ax_export_status_manual"},
          :product_category => {label: "Product Category", data_type: :string, module_type: "Product", cdef_uid: "prod_product_category"},
          :rl_short_description => {label: "RL Short Description", data_type: :string, module_type: "Product", cdef_uid: "prod_rl_short_description"},
          :rl_long_description => {label: "RL Long Description", data_type: :text, module_type: "Product", cdef_uid: "prod_rl_long_description"},
          :heel_height => {label: "Heel Height", data_type: :string, module_type: "Product", cdef_uid: "prod_heel_height"},
          :sap_brand_name => {label: "SAP Brand Name", data_type: :string, module_type: "Product", cdef_uid: "prod_sap_brand_name"},
          :gcc_description_2 => {label: "GCC Description 2", data_type: :string, module_type: "Product", cdef_uid: "prod_gcc_description_2"},
          :gcc_description_3 => {label: "GCC Description 3", data_type: :string, module_type: "Product", cdef_uid: "prod_gcc_description_3"},
          :non_textile => {label: "Non Textile", data_type: :string, module_type: "Product", cdef_uid: "prod_non_textile"},
          :depth_in => {label: "Depth (in.)", data_type: :decimal, module_type: "Product", cdef_uid: "prod_depth_in"},
          :width_bottom_in => {label: "Width Bottom (in.)", data_type: :decimal, module_type: "Product", cdef_uid: "prod_width_bottom_in"},
          :height_in => {label: "Height (in.)", data_type: :decimal, module_type: "Product", cdef_uid: "prod_height_in"},
          :rl_merchandise_division_description => {label: "RL Merchandise Division Description", data_type: :string, module_type: "Product", cdef_uid: "prod_rl_merchandise_division_description"},
          :depth_cm => {label: "Depth (cm)", data_type: :decimal, module_type: "Product", cdef_uid: "prod_depth_cm"},
          :bottom_width_cm => {label: "Bottom Width (cm)", data_type: :decimal, module_type: "Product", cdef_uid: "prod_bottom_width_cm"}
        }

        included do |base|
          base.extend(::OpenChain::CustomHandler::CustomDefinitionSupport)
        end
        
        module ClassMethods
          def prep_custom_definitions fields
            prep_custom_defs fields, CUSTOM_DEFINITION_INSTRUCTIONS
          end
        end
      end
    end
  end
end
