require 'open_chain/custom_handler/custom_definition_support'
module OpenChain
  module CustomHandler
    module Polo
      module PoloCustomDefinitionSupport
        extend ActiveSupport::Concern

        CUSTOM_DEFINITION_INSTRUCTIONS = {
          :ord_division => {label: "Merchandise Division", data_type: :string, module_type: "Order"},
          :ord_line_ex_factory_date => {label: "Planned Ex-Factory", data_type: :date, module_type: "OrderLine"},
          :ord_line_ship_mode => {label: "Ship Mode", data_type: :string, module_type: "OrderLine"},
          :ord_line_board_number => {label: "Board Number", data_type: :string, module_type: "OrderLine"},
          :bartho_customer_id=>{:label=>"Barthco Customer ID", :data_type=>:string, :module_type=>'Product'},
          :season=>{:label=>"Season", :data_type => :string, :module_type=>'Product'},
          :test_style=>{:label=>"Test Style", :data_type=>:string, :module_type=>'Product'},
          :set_type=>{:label=>"Set Type", :data_type=>:string, :module_type=>'Classification'},
          :merch_division=>{:label=>'Merch Div Desc', :data_type=>:string, :module_type=>'Product'},
          :csm_numbers => {:label=>'CSM Number', :data_type=>:text, :module_type=>'Product'},
          :fiber_content => {:label=>'Fiber Content %s', :data_type=>:string, :module_type=>'Product'},
          :fabric_type_1 => {label: 'Fabric Type - 1', data_type: :string, module_type: "Product"},
          :fabric_1 => {label: 'Fabric - 1', data_type: :string, module_type: "Product"},
          :fabric_percent_1 => {label: 'Fabric % - 1', data_type: :decimal, module_type: "Product"},
          :fabric_type_2 => {label: 'Fabric Type - 2', data_type: :string, module_type: "Product"},
          :fabric_2 => {label: 'Fabric - 2', data_type: :string, module_type: "Product"},
          :fabric_percent_2 => {label: 'Fabric % - 2', data_type: :decimal, module_type: "Product"},
          :fabric_type_3 => {label: 'Fabric Type - 3', data_type: :string, module_type: "Product"},
          :fabric_3 => {label: 'Fabric - 3', data_type: :string, module_type: "Product"},
          :fabric_percent_3 => {label: 'Fabric % - 3', data_type: :decimal, module_type: "Product"},
          :fabric_type_4 => {label: 'Fabric Type - 4', data_type: :string, module_type: "Product"},
          :fabric_4 => {label: 'Fabric - 4', data_type: :string, module_type: "Product"},
          :fabric_percent_4 => {label: 'Fabric % - 4', data_type: :decimal, module_type: "Product"},
          :fabric_type_5 => {label: 'Fabric Type - 5', data_type: :string, module_type: "Product"},
          :fabric_5 => {label: 'Fabric - 5', data_type: :string, module_type: "Product"},
          :fabric_percent_5 => {label: 'Fabric % - 5', data_type: :decimal, module_type: "Product"},
          :fabric_type_6 => {label: 'Fabric Type - 6', data_type: :string, module_type: "Product"},
          :fabric_6 => {label: 'Fabric - 6', data_type: :string, module_type: "Product"},
          :fabric_percent_6 => {label: 'Fabric % - 6', data_type: :decimal, module_type: "Product"},
          :fabric_type_7 => {label: 'Fabric Type - 7', data_type: :string, module_type: "Product"},
          :fabric_7 => {label: 'Fabric - 7', data_type: :string, module_type: "Product"},
          :fabric_percent_7 => {label: 'Fabric % - 7', data_type: :decimal, module_type: "Product"},
          :fabric_type_8 => {label: 'Fabric Type - 8', data_type: :string, module_type: "Product"},
          :fabric_8 => {label: 'Fabric - 8', data_type: :string, module_type: "Product"},
          :fabric_percent_8 => {label: 'Fabric % - 8', data_type: :decimal, module_type: "Product"},
          :fabric_type_9 => {label: 'Fabric Type - 9', data_type: :string, module_type: "Product"},
          :fabric_9 => {label: 'Fabric - 9', data_type: :string, module_type: "Product"},
          :fabric_percent_9 => {label: 'Fabric % - 9', data_type: :decimal, module_type: "Product"},
          :fabric_type_10 => {label: 'Fabric Type - 10', data_type: :string, module_type: "Product"},
          :fabric_10 => {label: 'Fabric - 10', data_type: :string, module_type: "Product"},
          :fabric_percent_10 => {label: 'Fabric % - 10', data_type: :decimal, module_type: "Product"},
          :fabric_type_11 => {label: 'Fabric Type - 11', data_type: :string, module_type: "Product"},
          :fabric_11 => {label: 'Fabric - 11', data_type: :string, module_type: "Product"},
          :fabric_percent_11 => {label: 'Fabric % - 11', data_type: :decimal, module_type: "Product"},
          :fabric_type_12 => {label: 'Fabric Type - 12', data_type: :string, module_type: "Product"},
          :fabric_12 => {label: 'Fabric - 12', data_type: :string, module_type: "Product"},
          :fabric_percent_12 => {label: 'Fabric % - 12', data_type: :decimal, module_type: "Product"},
          :fabric_type_13 => {label: 'Fabric Type - 13', data_type: :string, module_type: "Product"},
          :fabric_13 => {label: 'Fabric - 13', data_type: :string, module_type: "Product"},
          :fabric_percent_13 => {label: 'Fabric % - 13', data_type: :decimal, module_type: "Product"},
          :fabric_type_14 => {label: 'Fabric Type - 14', data_type: :string, module_type: "Product"},
          :fabric_14 => {label: 'Fabric - 14', data_type: :string, module_type: "Product"},
          :fabric_percent_14 => {label: 'Fabric % - 14', data_type: :decimal, module_type: "Product"},
          :fabric_type_15 => {label: 'Fabric Type - 15', data_type: :string, module_type: "Product"},
          :fabric_15 => {label: 'Fabric - 15', data_type: :string, module_type: "Product"},
          :fabric_percent_15 => {label: 'Fabric % - 15', data_type: :decimal, module_type: "Product"},
          :msl_fiber_failure => {label: "MSL Fiber Failure", data_type: :boolean, module_type: "Product"},
          :length_cm => {label: "Length (cm)", data_type: :decimal, module_type: "Product"},
          :width_cm => {label: "Width (cm)", data_type: :decimal, module_type: "Product"},
          :height_cm => {label: "Height (cm)", data_type: :decimal, module_type: "Product"},
          :msl_receive_date => {label: "MSL+ Receive Date", data_type: :date, module_type: "Product"},
          :msl_us_class => {label: "MSL+ US Class", data_type: :string, module_type: "Product"},
          :msl_us_brand => {label: "MSL+ US Brand", data_type: :string, module_type: "Product"},
          :msl_us_sub_brand => {label: "MSL+ US Sub Brand", data_type: :string, module_type: "Product"},
          :msl_model_desc => {label: "MSL+ Model Description", data_type: :string, module_type: "Product"},
          :msl_hts_desc => {label: "MSL+ HTS Description", data_type: :string, module_type: "Product"},
          :msl_hts_desc_2 => {label: "MSL+ HTS Description 2", data_type: :string, module_type: "Product"},
          :msl_hts_desc_3 => {label: "MSL+ HTS Description 3", data_type: :string, module_type: "Product"},
          :ax_subclass => {label: "AX Subclass", data_type: :string, module_type: "Product"},
          :msl_item_desc => {label: "MSL+ Item Description", data_type: :string, module_type: "Product"},
          :msl_us_season => {label: "MSL+ US Season", data_type: :string, module_type: "Product"},
          :msl_gcc_desc => {label: "GCC Description", data_type: :string, module_type: "Product"},
          :msl_board_number => {label: "Board Number", data_type: :string, module_type: "Product"},
          :common_name_1 => {label: "Common Name 1", data_type: :string, module_type: "Product"},
          :common_name_2 => {label: "Common Name 2", data_type: :string, module_type: "Product"},
          :common_name_3 => {label: "Common Name 3", data_type: :string, module_type: "Product"},
          :common_name_4 => {label: "Common Name 4", data_type: :string, module_type: "Product"},
          :common_name_5 => {label: "Common Name 5", data_type: :string, module_type: "Product"},
          :scientific_name_1 => {label: "Scientific Name 1", data_type: :string, module_type: "Product"},
          :scientific_name_2 => {label: "Scientific Name 2", data_type: :string, module_type: "Product"},
          :scientific_name_3 => {label: "Scientific Name 3", data_type: :string, module_type: "Product"},
          :scientific_name_4 => {label: "Scientific Name 4", data_type: :string, module_type: "Product"},
          :scientific_name_5 => {label: "Scientific Name 5", data_type: :string, module_type: "Product"},
          :fish_wildlife_origin_1 => {label: "F&W Origin 1", data_type: :string, module_type: "Product"},
          :fish_wildlife_origin_2 => {label: "F&W Origin 2", data_type: :string, module_type: "Product"},
          :fish_wildlife_origin_3 => {label: "F&W Origin 3", data_type: :string, module_type: "Product"},
          :fish_wildlife_origin_4 => {label: "F&W Origin 4", data_type: :string, module_type: "Product"},
          :fish_wildlife_origin_5 => {label: "F&W Origin 5", data_type: :string, module_type: "Product"},
          :fish_wildlife_source_1 => {label: "F&W Source 1", data_type: :string, module_type: "Product"},
          :fish_wildlife_source_2 => {label: "F&W Source 2", data_type: :string, module_type: "Product"},
          :fish_wildlife_source_3 => {label: "F&W Source 3", data_type: :string, module_type: "Product"},
          :fish_wildlife_source_4 => {label: "F&W Source 4", data_type: :string, module_type: "Product"},
          :fish_wildlife_source_5 => {label: "F&W Source 5", data_type: :string, module_type: "Product"},
          :origin_wildlife => {label: "Origin of Wildlife", data_type: :string, module_type: "Product"},
          :semi_precious => {label: "Semi-Precious", data_type: :boolean, module_type: "Product"},
          :semi_precious_type => {label: "Type of Semi-Precious", data_type: :string, module_type: "Product"},
          :cites => {label: "CITES", data_type: :boolean, module_type: "Product"},
          :fish_wildlife => {label: "Fish & Wildlife", data_type: :boolean, module_type: "Product"},
          :msl_fiber_status => {label: "MSL Fiber Status", data_type: :string, module_type: "Product"},
          :product_area => {label: "Product Area", data_type: :string, module_type: "Product"},
          :long_description => {label: "Long Description", data_type: :text, module_type: "Product"},
          :stitch_count_vertical => {label: "Stitch Count / 2cm Vertical", data_type: :string, module_type: "Product"},
          :stitch_count_horizontal => {label: "Stitch Count / 2cm Horizontal", data_type: :string, module_type: "Product"},
          :grams_square_meter => {label: "Grams / Square Meter", data_type: :string, module_type: "Product"},
          :knit_type => {label: "Knit Type (Jersey, mesh, etc)", data_type: :string, module_type: "Product"},
          :type_of_bottom => {label: "Type of Bottom (Hemmed, ribbed,etc)", data_type: :string, module_type: "Product"},
          :functional_neck_closure => {label: "Functional Neck Closure", data_type: :boolean, module_type: "Product"},
          :significantly_napped => {label: "Significantly Napped", data_type: :boolean, module_type: "Product"},
          :back_type => {label: "Back Type / Shape", data_type: :string, module_type: "Product"},
          :defined_armholes => {label: "Defined Armholes", data_type: :boolean, module_type: "Product"},
          :strap_width => {label: "Strap Width (in.)", data_type: :string, module_type: "Product"},
          :pass_water_resistant_test => {label: "Pass Water Resistant Test AATC35-2006", data_type: :string, module_type: "Product"},
          :type_of_coating => {label: "Type of Coating", data_type: :string, module_type: "Product"},
          :padding_or_filling => {label: "Padding or Filling?", data_type: :string, module_type: "Product"},
          :meets_down_requirments => {label: "Meets Down Requirements", data_type: :boolean, module_type: "Product"},
          :tightening_at_waist => {label: "Tightening at Waist (Cord, Ribbing, etc)", data_type: :string, module_type: "Product"},
          :denim => {label: "Denim", data_type: :string, module_type: "Product"},
          :denim_color => {label: "Denim color", data_type: :string, module_type: "Product"},
          :corduroy => {label: "Corduroy", data_type: :boolean, module_type: "Product"},
          :shearling => {label: "Shearling", data_type: :boolean, module_type: "Product"},
          :total_back_panels => {label: "Total # of Back Panels", data_type: :integer, module_type: "Product"},
          :short_fall_above_knee => {label: "Short Fall Above Knee", data_type: :boolean, module_type: "Product"},
          :mesh_lining => {label: "Mesh Lining", data_type: :boolean, module_type: "Product"},
          :full_elastic_waistband => {label: "Full Elastic Waistband", data_type: :boolean, module_type: "Product"},
          :full_functional_drawstring => {label: "Full Functional Drawstring", data_type: :boolean, module_type: "Product"},
          :cover_crown_of_head => {label: "Cover Crown Of Head", data_type: :boolean, module_type: "Product"},
          :wholly_or_partially_braid => {label: "Wholly or Partially Braid", data_type: :string, module_type: "Product"},
          :yarn_dyed => {label: "Yarn Dyed", data_type: :string, module_type: "Product"},
          :colors_in_warp_weft => {label: "# of Colors in Warp / Weft", data_type: :string, module_type: "Product"},
          :piece_dyed => {label: "Piece Dyed", data_type: :boolean, module_type: "Product"},
          :printed => {label: "Printed", data_type: :boolean, module_type: "Product"},
          :solid => {label: "Solid", data_type: :boolean, module_type: "Product"},
          :ounces_sq_yd => {label: "Ounces / Sq Yd", data_type: :decimal, module_type: "Product"},
          :size_scale => {label: "Size Scale (S/M/L or 15/16/17)", data_type: :string, module_type: "Product"},
          :type_of_fabric => {label: "Type of Fabric (velour, velvet, etc)", data_type: :string, module_type: "Product"},
          :weight_of_fabric => {label: "Weight of Fabric", data_type: :string, module_type: "Product"},
          :form_fitting_or_loose_fitting => {label: "Form Fitting or Loose Fitting", data_type: :string, module_type: "Product"},
          :functional_open_fly => {label: "Functional Open Fly", data_type: :boolean, module_type: "Product"},
          :fly_covered => {label: "Fly Covered With Open Placket", data_type: :boolean, module_type: "Product"},
          :tightening_at_cuffs => {label: "Tightening At Cuffs", data_type: :boolean, module_type: "Product"},
          :embellishments_or_ornamentation => {label: "Embellishments or Ornamentation", data_type: :boolean, module_type: "Product"},
          :sizing => {label: "Sizing", data_type: :string, module_type: "Product"},
          :sold_in_sleepwear_dept => {label: "Sold In Sleepwear Dept.", data_type: :boolean, module_type: "Product"},
          :pcs_in_set => {label: "# pcs. in set", data_type: :integer, module_type: "Product"},
          :sold_as_set => {label: "If more than 1 pc, sold as set?", data_type: :boolean, module_type: "Product"},
          :footwear_upper => {label: "Footwear Upper", data_type: :string, module_type: "Product"},
          :footwear_outsole => {label: "Footwear Outsole", data_type: :string, module_type: "Product"},
          :welted => {label: "Welted", data_type: :boolean, module_type: "Product"},
          :cover_the_ankle => {label: "Does it completely cover the ankle?", data_type: :boolean, module_type: "Product"},
          :secure_closure => {label: "Secure Closure", data_type: :boolean, module_type: "Product"},
          :closure_type => {label: "Closure Type", data_type: :string, module_type: "Product"},
          :multiple_compartment => {label: "Multiple Compartment", data_type: :boolean, module_type: "Product"},
          :fourchettes_for_gloves => {label: "Fourchettes for Gloves", data_type: :boolean, module_type: "Product"},
          :lined_for_gloves => {label: "Lined for Gloves", data_type: :boolean, module_type: "Product"},
          :seamed => {label: "Seamed", data_type: :boolean, module_type: "Product"},
          :components => {label: "Components", data_type: :string, module_type: "Product"},
          :cost_of_component => {label: "Cost of Component", data_type: :string, module_type: "Product"},
          :weight_of_components => {label: "Weight of Components", data_type: :string, module_type: "Product"},
          :material_content_of_posts_earrings => {label: "Material Content of Posts - Earrings", data_type: :string, module_type: "Product"},
          :filled => {label: "Filled", data_type: :boolean, module_type: "Product"},
          :type_of_fill => {label: "Type of Fill", data_type: :string, module_type: "Product"},
          :coated => {label: "Is the fabric coated?", data_type: :boolean, module_type: "Product"},
          :telescopic_shaft => {label: "Telescopic Shaft", data_type: :boolean, module_type: "Product"},
          :unit_price => {label: "Unit Price", data_type: :decimal, module_type: "Product"},
          :vendor_code => {label: "Vendor Code", data_type: :string, module_type: "Product"},
          :country_of_origin => {label: "Country of Origin", data_type: :string, module_type: "Product"},
          :common_name_fw => {label: "Common Name (F&W)", data_type: :string, module_type: "Product"},
          :scientific_name => {label: "Scientific Name", data_type: :string, module_type: "Product"},
          :source_indicator => {label: "Source Indicator", data_type: :string, module_type: "Product"},
          :royalty_percentage => {label: "Royalty %", data_type: :decimal, module_type: "Product"},
          :binding_ruling_number => {label: "Binding Ruling Number", data_type: :string, module_type: "Classification"},
          :binding_ruling_type => {label: "Binding Ruling Type", data_type: :string, module_type: "Classification"},
          :mid => {label: "MID", data_type: :string, module_type: "Classification"},
          :fda_product_code => {label: "FDA Product Code", data_type: :string, module_type: "Classification"},
          :effective_date => {label: "Effective Date", data_type: :date, module_type: "Product"},
          :price_uom => {label: "Price UOM", data_type: :string, module_type: "Product"},
          :special_program_indicator => {label: "Special Program Indicator", data_type: :string, module_type: "Classification"},
          :cvd_case => {label: "CVD Case #", data_type: :string, module_type: "Classification"},
          :add_case => {label: "ADD Case #", data_type: :string, module_type: "Classification"},
          :ptp_code => {label: "PTP Code", data_type: :string, module_type: "Product"},
          :terms_of_sale => {label: "Terms of Sale", data_type: :string, module_type: "Product"},
          :worsted_wool => {label: "Worsted Wool", data_type: :boolean, module_type: "Product"},
          :microns => {label: "# of Microns", data_type: :string, module_type: "Product"},
          :infant_diaper_cover => {label: "Infant Diaper Cover", data_type: :boolean, module_type: "Product"},
          :lining => {label: "Lining", data_type: :string, module_type: "Product"},
          :trim => {label: "Trim", data_type: :string, module_type: "Product"},
          :lin_number => {label: "LIN Number", data_type: :string, module_type: "Product"},
          :chart_comments => {label: "Chart Comments", data_type: :text, module_type: "Product"},
          :measurement_per_single_yarn => {label: "Measurement per single yarn < 67 decitex", data_type: :string, module_type: "Product"},
          :peaked_caps => {label: "Peaked caps", data_type: :string, module_type: "Product"},
          :weight_per_garment => {label: "Weight per Garment > 1kg?", data_type: :string, module_type: "Product"},
          :knee_length_stockings => {label: "Knee Length Stockings?", data_type: :string, module_type: "Product"},
          :country_description => {label: "Country Description", data_type: :text, module_type: "Classification"},
          :digit_style_9 => {label: "9 Digit Style No. ", data_type: :string, module_type: "Product"},
          :digit_style_6 => {label: "6 Digit Style No.", data_type: :string, module_type: "Product"},
          :factory_name => {label: "Factory Name", data_type: :text, module_type: "Product"},
          :production_manager => {label: "Production Manager", data_type: :string, module_type: "Product"},
          :eu_approved => {label: "EU Approved", data_type: :string, module_type: "Product"},
          :pillowcase => {label: "Is it a Pillowcase?", data_type: :string, module_type: "Product"},
          :pillowcover => {label: "Is it a Pillowcover?", data_type: :string, module_type: "Product"},
          :pillow => {label: "Is it a Pillow?", data_type: :string, module_type: "Product"},
          :content_for_filling_of_pillow => {label: "Content for filling of Pillow", data_type: :text, module_type: "Product"},
          :bolster_case => {label: "Is it a bolster case?", data_type: :string, module_type: "Product"},
          :napped => {label: "Is it napped?", data_type: :string, module_type: "Product"},
          # Yes, they have two different types of fields to determine if a product is printed...awesome
          :is_it_printed => {label: "Is it printed?", data_type: :string, module_type: "Product"},
          :embroidered => {label: "Does it contain any embro., lace, braid, edging, trim, piping or applique?", data_type: :string, module_type: "Product"},
          :quilted => {label: "Is it quilted?", data_type: :string, module_type: "Product"},
          :piping_exceed => {label: "Does piping exceed 6.35mm?", data_type: :string, module_type: "Product"},
          :silk_gt_50 => {label: "Is silk =>50% by wt. incl. lining of tie?", data_type: :string, module_type: "Product"},
          :sunglasses => {label: "Sunglasses", data_type: :string, module_type: "Product"},
          :fws_3177 => {label: "FWS 3177", data_type: :string, module_type: "Product"},
          :sap_brand => {label: "SAP Brand", data_type: :boolean, module_type: "Product"},
          :csm_department => {label: "CSM Department", data_type: :string, module_type: "Product"},
          :csm_season => {label: "CSM Season", data_type: :text, module_type: "Product"},
          :csm_received_date_first => {label: "CSM Received Date (First)", data_type: :date, module_type: "Product"},
          :csm_received_date_last => {label: "CSM Received Date (Last)", data_type: :date, module_type: "Product"},
          :knotted => {label: "Is it Knotted?", data_type: :boolean, module_type: "Product"},
          :woven => {label: "Is it woven incl. Schumacks, Karamanie, Kelem or sim. hand woven rugs?", data_type: :boolean, module_type: "Product"},
          :tufted => {label: "Is it tufted?", data_type: :boolean, module_type: "Product"},
          :area_measurement => {label: "Is the area measurement < 5.25 square meters?", data_type: :boolean, module_type: "Product"},
          :felt => {label: "Is it made of felt?", data_type: :boolean, module_type: "Product"},
          :coir => {label: "Is it made of coir?", data_type: :boolean, module_type: "Product"},
          :needlepoint => {label: "Is it made from needlepoint?", data_type: :boolean, module_type: "Product"},
          :gender_desc => {label: "Gender Desc", data_type: :string, module_type: "Product"},
          :suffix_indicator => {label: "Suffix Indicator", data_type: :string, module_type: "Product"},
          :exception_code => {label: "Exception Code", data_type: :string, module_type: "Product"},
          :suffix => {label: "Suffix", data_type: :string, module_type: "Product"},
          :comments => {label: "Comments", data_type: :text, module_type: "Product"},
          :part_number => {label: "Part Number", data_type: :string, module_type: "Product"},
          :cover_the_calf => {label: "Does it cover the calf ? ", data_type: :boolean, module_type: "Product"},
          :vamp_made_of_straps => {label: "Is vamp made of straps of which has one or several pieces cut out? ", data_type: :boolean, module_type: "Product"},
          :height_gt_3_cm => {label: "With the sole and heel combined have a height of more than 3 cm.?", data_type: :boolean, module_type: "Product"},
          :platform_of_wood => {label: "Is it made on a base or platform of wood or cork?", data_type: :string, module_type: "Product"},
          :inner_sole => {label: "Does it have an inner sole?", data_type: :boolean, module_type: "Product"},
          :protective_metal_toe_cap => {label: "Does it have a protective metal toe cap?", data_type: :boolean, module_type: "Product"},
          :upper_leather_straps => {label: "Does the upper consist of leather straps across the instep and around the big toe?", data_type: :boolean, module_type: "Product"},
          :turned_footwear => {label: "Is it turned footwear?", data_type: :boolean, module_type: "Product"},
          :test_required => {label: "Test Required", data_type: :boolean, module_type: "Product"},
          :cover_the_knee => {label: "Does it cover the knee?", data_type: :boolean, module_type: "Product"},
          :footwear_waterproof => {label: "Is the footwear waterproof?", data_type: :boolean, module_type: "Product"},
          :footwear_lined_with_textile => {label: "Is the footwear lined with textile fabric?", data_type: :boolean, module_type: "Product"},
          :uppers_gt_90_esau => {label: "Does the footwear have uppers of which 90% of the ESAU (including accessories/reinforcements rubber/plastic? ", data_type: :boolean, module_type: "Product"},
          :zoris => {label: "Does it have a Zoris? ", data_type: :boolean, module_type: "Product"},
          :open_toes => {label: "Open toes or open heels?", data_type: :boolean, module_type: "Product"},
          :slip_on_type => {label: "Slip on type that is held to the foot without use of laces, buckles or other fasteners?", data_type: :boolean, module_type: "Product"},
          :protection_against_water => {label: "Does it provide protection against water or cold/inclement weather?", data_type: :boolean, module_type: "Product"},
          :one_piece_by_molding => {label: "For sandals and similar footwear of plastics, is it produced in one piece by molding?", data_type: :boolean, module_type: "Product"},
          :foxing => {label: "Foxing?", data_type: :boolean, module_type: "Product"},
          :weight_of_rubber_plastic_lt_10 => {label: "Is the weight of the rubber/plastic less than 10% of the entire shoe?", data_type: :boolean, module_type: "Product"},
          :rubber_plastic_soles => {label: "Does it have rubber/plastic soles which are affixed to the upper exclusively with an adhesive?", data_type: :boolean, module_type: "Product"},
          :weight_of_rubber_plastic_lt50 => {label: "Is the weight of the rubber, plastic and textile less than 50% of the entire shoe?", data_type: :boolean, module_type: "Product"},
          :uppers_gt_50_esau => {label: "Does the footwear have uppers of which over 50% of the ESAU including leather accessories/reinforcements is leather?", data_type: :boolean, module_type: "Product"},
          :vendor_name => {label: "Vendor Name", data_type: :string, module_type: "Product"},
          :ic_number => {label: "IC #", data_type: :string, module_type: "Product"},
          :licensee_product => {label: "Licensee Product", data_type: :boolean, module_type: "Product"},
          :num_of_sides_fringes => {label: "# of sides (fringes)", data_type: :string, module_type: "Product"},
          :functional_or_decorative => {label: "Functional or Decorative", data_type: :string, module_type: "Product"},
          :flanelle_percale => {label: "Flanelle, Percale or Other", data_type: :string, module_type: "Product"},
          # This knit_woven field is a replacement for the old "Knit / Woven?" field.  The old "Knit / Woven?" field became "Material Group (Deprecated)"
          :knit_woven => {label: "Knit / Woven", data_type: :string, module_type: "Product"},
          :material_group => {label: "Material Group (Deprecated)", data_type: :string, module_type: "Product"},
          :allocation_category => {label: "Allocation Category", data_type: :string, module_type: "Product"}
        }

        included do |base|
          base.extend(::OpenChain::CustomHandler::CustomDefinitionSupport)
        end
        
        module ClassMethods
          def prep_custom_definitions fields
            prep_custom_defs fields, CUSTOM_DEFINITION_INSTRUCTIONS
          end
        end
      end
    end
  end
end
