require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PowerOfAttorneysController do

  # This should return the minimal set of attributes required to create a valid
  # PowerOfAttorney. As you add validations to PowerOfAttorney, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all power_of_attorneys as @power_of_attorneys" do
      power_of_attorney = PowerOfAttorney.create! valid_attributes
      get :index
      assigns(:power_of_attorneys).should eq([power_of_attorney])
    end
  end

  describe "GET show" do
    it "assigns the requested power_of_attorney as @power_of_attorney" do
      power_of_attorney = PowerOfAttorney.create! valid_attributes
      get :show, :id => power_of_attorney.id.to_s
      assigns(:power_of_attorney).should eq(power_of_attorney)
    end
  end

  describe "GET new" do
    it "assigns a new power_of_attorney as @power_of_attorney" do
      get :new
      assigns(:power_of_attorney).should be_a_new(PowerOfAttorney)
    end
  end

  describe "GET edit" do
    it "assigns the requested power_of_attorney as @power_of_attorney" do
      power_of_attorney = PowerOfAttorney.create! valid_attributes
      get :edit, :id => power_of_attorney.id.to_s
      assigns(:power_of_attorney).should eq(power_of_attorney)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PowerOfAttorney" do
        expect {
          post :create, :power_of_attorney => valid_attributes
        }.to change(PowerOfAttorney, :count).by(1)
      end

      it "assigns a newly created power_of_attorney as @power_of_attorney" do
        post :create, :power_of_attorney => valid_attributes
        assigns(:power_of_attorney).should be_a(PowerOfAttorney)
        assigns(:power_of_attorney).should be_persisted
      end

      it "redirects to the created power_of_attorney" do
        post :create, :power_of_attorney => valid_attributes
        response.should redirect_to(PowerOfAttorney.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved power_of_attorney as @power_of_attorney" do
        # Trigger the behavior that occurs when invalid params are submitted
        PowerOfAttorney.any_instance.stub(:save).and_return(false)
        post :create, :power_of_attorney => {}
        assigns(:power_of_attorney).should be_a_new(PowerOfAttorney)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PowerOfAttorney.any_instance.stub(:save).and_return(false)
        post :create, :power_of_attorney => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested power_of_attorney" do
        power_of_attorney = PowerOfAttorney.create! valid_attributes
        # Assuming there are no other power_of_attorneys in the database, this
        # specifies that the PowerOfAttorney created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PowerOfAttorney.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => power_of_attorney.id, :power_of_attorney => {'these' => 'params'}
      end

      it "assigns the requested power_of_attorney as @power_of_attorney" do
        power_of_attorney = PowerOfAttorney.create! valid_attributes
        put :update, :id => power_of_attorney.id, :power_of_attorney => valid_attributes
        assigns(:power_of_attorney).should eq(power_of_attorney)
      end

      it "redirects to the power_of_attorney" do
        power_of_attorney = PowerOfAttorney.create! valid_attributes
        put :update, :id => power_of_attorney.id, :power_of_attorney => valid_attributes
        response.should redirect_to(power_of_attorney)
      end
    end

    describe "with invalid params" do
      it "assigns the power_of_attorney as @power_of_attorney" do
        power_of_attorney = PowerOfAttorney.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PowerOfAttorney.any_instance.stub(:save).and_return(false)
        put :update, :id => power_of_attorney.id.to_s, :power_of_attorney => {}
        assigns(:power_of_attorney).should eq(power_of_attorney)
      end

      it "re-renders the 'edit' template" do
        power_of_attorney = PowerOfAttorney.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PowerOfAttorney.any_instance.stub(:save).and_return(false)
        put :update, :id => power_of_attorney.id.to_s, :power_of_attorney => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested power_of_attorney" do
      power_of_attorney = PowerOfAttorney.create! valid_attributes
      expect {
        delete :destroy, :id => power_of_attorney.id.to_s
      }.to change(PowerOfAttorney, :count).by(-1)
    end

    it "redirects to the power_of_attorneys list" do
      power_of_attorney = PowerOfAttorney.create! valid_attributes
      delete :destroy, :id => power_of_attorney.id.to_s
      response.should redirect_to(power_of_attorneys_url)
    end
  end

end
